### PR TITLE
fix(util-mock): fix chokidar.watch choking on mock db-journal

### LINKED ISSUE #11657: mock api EPERM: operation not permitted, lstat
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.5.2

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

While running `amplify mock api` and rapidly ingesting data, the amplify-cli will encounter an error: `EPERM: operation not permitted, lstat`

### Expected behavior

Rapid ingest shouldn't be a problem with the mock api.

### Reproduction steps

1. Create a mock api.
2. Submit 1000's of transactions into the database.
3. CLI encounters error.

### Project Identifier

Session Identifier: dc189b9e-1161-417d-a293-14ef4e786d81

### Log output

<details>

```
2022-12-24T23:55:11.660Z|error : EPERM: operation not permitted, lstat 'C:\Users\test\trading\src\test\amplify\mock-data\dynamodb\fake_us-fake-1.db-journal'
UnknownNodeJSFault: EPERM: operation not permitted, lstat 'C:\Users\test\trading\src\test\amplify\mock-data\dynamodb\fake_us-fake-1.db-journal'

```

</details>

### Additional information

The watch on the mockDataDirectory throws the error when the `.db-journal` flashes into existence and then is removed.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### PR DESCRIPTION
**Pull request by joekiller**
fixes #11657

#### Description of changes

This fixes the dynamo local journal causing lstat issues.

#### Description of how you validated changes
I tested with adding many transactions to the system. With the fix the mock setup doesn't error when the journal appears briefly.
#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [x] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jhockett** [comment]
Thanks for tracking this down and contributing a fix @joekiller!

Something went wrong with our PR automation, would you mind rebasing and force pushing again to see if that resolves the issue?

**Comment by joekiller** [comment]
> you mind rebasing and force pushing again to see if that resolves the issue?

@jhockett I have done as requested. I'm unsure if the ci issue is resolved.

**Comment by jhockett** [comment]
Thanks for trying @joekiller, it's still not executing the full PR workflow in CircleCI, but I'm not sure why.

Here's the error message:
```
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.
```

Did you disable a permission related to CircleCI in your GitHub account settings?

**Comment by danielleadams** [comment]
@joekiller were you able to check your Circle CI configuration?

**Comment by joekiller** [comment]
@jhockett @danielleadams apologies it was unclear to me that I needed to grant circle ci authorization to read my public information. I've done so now and will try to get it to trigger again with a force push.

**Comment by danielleadams** [comment]
@joekiller no worries - I've started the integration tests for you.

**Review by jhockett — APPROVED** [review]

**Review by alharris-at — APPROVED** [review]

**Pull request merged**
