### PR TITLE
chore: update api plugin dependencies

### PR DESCRIPTION
**Pull request by phani-srikar**
#### Description of changes

Updates dependencies on `API` plugin related packages as per the latest `API` plugin release https://github.com/aws-amplify/amplify-category-api/commit/143ac8408b0efc37928f421aac4002d44ef280cb
Update the mock plugin tests to remove references to `getString` FF method.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jhockett — APPROVED** [review]

**Comment by danielleadams** [comment]
@phani-srikar is this ready to run cloud e2e on?

**Comment by phani-srikar** [comment]
> @phani-srikar is this ready to run cloud e2e on?

We had another release this week. So the version bumps in this are outdated. I will ask on-call to update this one.

**Comment by marcvberg** [comment]
@danielleadams versions are bumped

**Comment by danielleadams** [comment]
@phani-srikar @marcvberg It looks like a GQL test is failing

**Review by danielleadams — CHANGES_REQUESTED** [review]
As mentioned in previous comment a test in the API is failing. (It looks like a snapshot needs to be updated.)

**Comment by danielleadams** [comment]
@phani-srikar is this PR still relevant since an API update already went out?

**Pull request closed without merging**
