### PR TITLE
fix(amplify-codegen-appsync-model-plugin): refactor the build step in java modelgen

### LINKED ISSUE #5046: AWS Amplify Modlegen Generate Android Studio Compilation Errors
Hi, I used the Amplify tutorial for Android Studio, for model generation. I have some compilation problems with Android. Do I need to implement the missing functionalities manually?

I'm using version 1.1.1.

Here's my schema:

```graphql
type Records @model {
  id: ID!
  user: String!
  vaccine_name: String
  vaccine_volume: Int
  injection_volume: Int
  bottle_volume: Int
  spray_name: String
  day_counter: Int
  batch_counter: Int
  replace_param: String
  temp_range: String
  location: String
} 
```

Here's the compilation failure:
```console
:app:compileDebugJavaWithJavac
app/src/main/java/com/amplifyframework/datastore/generated/model/Records.java
Builder is not abstract and does not override abstract method temp_range(String) in BuildStep
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
method does not override or implement a method from a supertype
cannot find symbol method vaccineName(String)
Compilation failed; see the compiler error output for 
```

I succeed to generate only when I used the screamer for all the fields.

### LINKED ISSUE #5444: [Android] Schema field names must be in camel case, or the generated code fails to build.
If strict camel case is not follow the generated models will fail to compile do to the capitalization issues. For example if “employeePID” is used as a field name in a model, the generated code will use “employeePID” and “employeePid” interchangeably. This results in a failed build with the error:

_error: Builder is not abstract and does not override abstract method employeePID(String) in BuildStep
  public static class Builder implements BuildStep {_

This behavior is also inconsistent with the iOS implementation. The model generation for iOS will handle these names without issue.

**Android versions:**

```groovy
implementation 'com.amplifyframework:core:1.3.2'
implementation 'com.amplifyframework:aws-api:1.3.2'
```

**iOS versions:**

```
  - Amplify (1.1.2):
    - Amplify/Default (= 1.1.2)
  - Amplify/Default (1.1.2)
  - Amplify/Tools (1.1.2)
  - AmplifyPlugins/AWSAPIPlugin (1.1.2):
    - AppSyncRealTimeClient (~> 1.4.0)
    - AWSAuthCore (~> 2.15.0)
    - AWSCore (~> 2.15.0)
    - AWSPluginsCore (= 1.1.2)
    - ReachabilitySwift (~> 5.0.0)
  - AmplifyPlugins/AWSDataStorePlugin (1.1.2):
    - AWSAuthCore (~> 2.15.0)
    - AWSCore (~> 2.15.0)
    - AWSPluginsCore (= 1.1.2)
    - SQLite.swift (~> 0.12.0)
  - AppSyncRealTimeClient (1.4.1):
    - Starscream (~> 3.1.0)
  - AWSAuthCore (2.15.3):
    - AWSCore (= 2.15.3)
  - AWSCognitoIdentityProvider (2.15.3):
    - AWSCognitoIdentityProviderASF (= 1.0.2)
    - AWSCore (= 2.15.3)
  - AWSCognitoIdentityProviderASF (1.0.2)
  - AWSCore (2.15.3)
  - AWSMobileClient (2.15.3):
    - AWSAuthCore (= 2.15.3)
    - AWSCognitoIdentityProvider (= 2.15.3)
  - AWSPluginsCore (1.1.2):
    - Amplify (= 1.1.2)
    - AWSCore (~> 2.15.0)
    - AWSMobileClient (~> 2.15.0)
  - CocoaAsyncSocket (7.6.4)
  - ReachabilitySwift (5.0.0)
  - SQLite.swift (0.12.2):
    - SQLite.swift/standard (= 0.12.2)
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.1.1)
```

**Example Model:**

```graphql
type Todo @model
{
   id: ID!
   employeePID: String
}
```

**Generated Model Code:**

```java
package com.amplifyframework.datastore.generated.model;

import java.util.List;
import java.util.UUID;
import java.util.Objects;

import androidx.core.util.ObjectsCompat;

import com.amplifyframework.core.model.Model;
import com.amplifyframework.core.model.annotations.Index;
import com.amplifyframework.core.model.annotations.ModelConfig;
import com.amplifyframework.core.model.annotations.ModelField;
import com.amplifyframework.core.model.query.predicate.QueryField;

import static com.amplifyframework.core.model.query.predicate.QueryField.field;

/** This is an auto generated class representing the Todo type in your schema. */
@SuppressWarnings("all")
@ModelConfig(pluralName = "Todos")
public final class Todo implements Model {
  public static final QueryField ID = field("id");
  public static final QueryField EMPLOYEE_PID = field("employeePID");
  private final @ModelField(targetType="ID", isRequired = true) String id;
  private final @ModelField(targetType="String") String employeePID;
  public String getId() {
      return id;
  }
  
  public String getEmployeePid() {
      return employeePID;
  }
  
  private Todo(String id, String employeePID) {
    this.id = id;
    this.employeePID = employeePID;
  }
  
  @Override
   public boolean equals(Object obj) {
      if (this == obj) {
        return true;
      } else if(obj == null || getClass() != obj.getClass()) {
        return false;
      } else {
      Todo todo = (Todo) obj;
      return ObjectsCompat.equals(getId(), todo.getId()) &&
              ObjectsCompat.equals(getEmployeePid(), todo.getEmployeePid());
      }
  }
  
  @Override
   public int hashCode() {
    return new StringBuilder()
      .append(getId())
      .append(getEmployeePid())
      .toString()
      .hashCode();
  }
  
  @Override
   public String toString() {
    return new StringBuilder()
      .append("Todo {")
      .append("id=" + String.valueOf(getId()) + ", ")
      .append("employeePID=" + String.valueOf(getEmployeePid()))
      .append("}")
      .toString();
  }
  
  public static BuildStep builder() {
      return new Builder();
  }
  
  /** 
   * WARNING: This method should not be used to build an instance of this object for a CREATE mutation.
   * This is a convenience method to return an instance of the object with only its ID populated
   * to be used in the context of a parameter in a delete mutation or referencing a foreign key
   * in a relationship.
   * @param id the id of the existing item this instance will represent
   * @return an instance of this model with only ID populated
   * @throws IllegalArgumentException Checks that ID is in the proper format
   */
  public static Todo justId(String id) {
    try {
      UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
    } catch (Exception exception) {
      throw new IllegalArgumentException(
              "Model IDs must be unique in the format of UUID. This method is for creating instances " +
              "of an existing object with only its ID field for sending as a mutation parameter. When " +
              "creating a new object, use the standard builder method and leave the ID field blank."
      );
    }
    return new Todo(
      id,
      null
    );
  }
  
  public CopyOfBuilder copyOfBuilder() {
    return new CopyOfBuilder(id,
      employeePID);
  }
  public interface BuildStep {
    Todo build();
    BuildStep id(String id) throws IllegalArgumentException;
    BuildStep employeePID(String employeePID);
  }
  

  public static class Builder implements BuildStep {
    private String id;
    private String employeePID;
    @Override
     public Todo build() {
        String id = this.id != null ? this.id : UUID.randomUUID().toString();
        
        return new Todo(
          id,
          employeePID);
    }
    
    @Override
     public BuildStep employeePid(String employeePid) {
        this.employeePID = employeePid;
        return this;
    }
    
    /** 
     * WARNING: Do not set ID when creating a new object. Leave this blank and one will be auto generated for you.
     * This should only be set when referring to an already existing object.
     * @param id id
     * @return Current Builder instance, for fluent method chaining
     * @throws IllegalArgumentException Checks that ID is in the proper format
     */
    public BuildStep id(String id) throws IllegalArgumentException {
        this.id = id;
        
        try {
            UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
        } catch (Exception exception) {
          throw new IllegalArgumentException("Model IDs must be unique in the format of UUID.",
                    exception);
        }
        
        return this;
    }
  }
  

  public final class CopyOfBuilder extends Builder {
    private CopyOfBuilder(String id, String employeePid) {
      super.id(id);
      super.employeePid(employeePid);
    }
    
    @Override
     public CopyOfBuilder employeePid(String employeePid) {
      return (CopyOfBuilder) super.employeePid(employeePid);
    }
  }
  
}
```

### PR DESCRIPTION
**Pull request by AaronZyLee**
*Issue #, if available:*
fix #5444 fix #5046 
*Description of changes:*
Used camel case instead of raw input from user for interface method to keep consistent with builder classes. The change only applies to modelgen output for Java.

### Sample Schema
```GraphQL
type Todo @model
{
   id: ID!
   taskPID: String
   subject_name: String
}
```
### Sample Output
```Java
public final class Todo implements Model {

  //class fields and methods...

  public interface BuildStep {
    Todo build();
    BuildStep id(String id) throws IllegalArgumentException;
    BuildStep taskPid(String taskPid);
    BuildStep subjectName(String subjectName);
  }
  

  public static class Builder implements BuildStep {
    private String id;
    private String taskPID;
    private String subject_name;
    @Override
     public Todo build() {
        String id = this.id != null ? this.id : UUID.randomUUID().toString();
        
        return new Todo(
          id,
          taskPID,
          subject_name);
    }
    
    @Override
     public BuildStep taskPid(String taskPid) {
        this.taskPID = taskPid;
        return this;
    }
    
    @Override
     public BuildStep subjectName(String subjectName) {
        this.subject_name = subjectName;
        return this;
    }
    
    public BuildStep id(String id) throws IllegalArgumentException {
    //..
  }
  

  public final class CopyOfBuilder extends Builder {
    private CopyOfBuilder(String id, String taskPid, String subjectName) {
      super.id(id);
      super.taskPid(taskPid)
        .subjectName(subjectName);
    }
    
    @Override
     public CopyOfBuilder taskPid(String taskPid) {
      return (CopyOfBuilder) super.taskPid(taskPid);
    }
    
    @Override
     public CopyOfBuilder subjectName(String subjectName) {
      return (CopyOfBuilder) super.subjectName(subjectName);
    }
  }
  
}
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TrekSoft** [comment]
I strongly disagree with altering what the customer specified in their schema to match some language conventions. Not only is this confusing to the customer but will also lead to conflicts if the customer has both subject_name and subjectName as two separate properties in their type (which is a legal thing to do).

We had this conversation before with @yuth during the code generation architecture that we should never change what the customer has in the schema unless we're technically unable to support it (in which case I would argue we should simply give them an error when they go to push that schema telling them which property is invalid and why).

**Review by TrekSoft — CHANGES_REQUESTED** [review]
See my comment

**Comment by richardmcclellan** [comment]
Hey @AaronZyLee, I would agree with @TrekSoft as well.  There are no customers using field names with underscores on Android today (due to this compile error you are fixing), so we should take this opportunity to make sure we get it right.  

Essentially all of the method names and and variable names should just match the field names - there should be no conversion to camel case.   The one exception to this is for the getters on the model - we should still capitalize the first letter and prepend `get`.  For example, a `title` field should generate a `getTitle()` getter method.  A `taskPID` field should generate a `getTaskPID()` method, and a `subject_name` field should generate a `getSubject_name()` method.  The Builder methods and variable names should match the field names exactly.

**Review by richardmcclellan — APPROVED** [review]
As discussed offline - we are going to disregard my previous comment and go with the first iteration of this PR, which converts everything to camel case.  Because of this, we will not be supporting models containing two field names with different case styles (e.g. `subjectName` and `subject_name`).   The reason for this is that these two fields would generate two instances of `QueryField SUBJECT_NAME`, which won't compile.

**Review by yuth — CHANGES_REQUESTED** [review]
Can you add validation when there is conflict with field names. If a schema has `due_date` and `dueDate` we should fail the codegen instead of discovering this at a later stage

**Review by yuth — APPROVED** [review]

**Pull request merged**
