### PR TITLE
Attempt to delete unused endpoints

### PR DESCRIPTION
**Pull request by GeorgeBellTMH**
Needed for: https://github.com/aws-amplify/amplify-js/pull/7733

Associated tickets:
https://github.com/aws-amplify/amplify-js/issues/7251#issuecomment-777602959
https://github.com/aws-amplify/amplify-js/issues/1378
https://github.com/aws-amplify/amplify-js/issues/5423

This reverts the following unexplained PR that caused these problems...
https://github.com/aws-amplify/amplify-cli/pull/5918

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
Also related to https://github.com/aws-amplify/amplify-ios/issues/946

**Comment by GeorgeBellTMH** [comment]
image

@SwaySway any more info on what is happening with this one? Would really like to get this resolved...

**Comment by kaustavghosh06** [comment]
@GeorgeBellTMH Why do we need this addition of IAM Policy. Looking at the issue you linked - https://github.com/aws-amplify/amplify-js/issues/5423#issuecomment-665456461 it looks like the amplify js library fixed this issue and doesn't require this IAM policy anymore.

**Comment by GeorgeBellTMH** [comment]
It was fixed in July....but In November both of these tickets (the one that fixed it in js and the one that fixed it in cli were removed). 

https://github.com/aws-amplify/amplify-js/pull/7245
https://github.com/aws-amplify/amplify-cli/pull/5918

And now there are tickets to re-add both of these un-explained changes...

This one...and:
https://github.com/aws-amplify/amplify-js/pull/7733

**Comment by GeorgeBellTMH** [comment]
To be explicit the method of cleaning up the end points in js requires listing the endpoints to figure out what to remove...and since both the cleanup and the permission have been removed, we now end up with the endpoints eventually not being able to be added.

**Comment by kaustavghosh06** [comment]
@GeorgeBellTMH Thanks for the detailed explanation. I'll be taking this up with the Amplify JS and pinpoint team and follow up with you soon. cc @sammartinez @manueliglesias

**Comment by GeorgeBellTMH** [comment]
Thanks!!!!

**Comment by renebrandel** [comment]
Hi @GeorgeBellTMH - we have been talking with the Pinpoint and Amplify JS team and have some more questions on this PR. Do you happen to have time to hop on a call with us? Email me anytime, so we can schedule it: renbran at amazon dot com.

**Comment by GeorgeBellTMH** [comment]
After discussions with Amazon it seems that it's unlikely that this PR will be accepted. My understanding is that due to existing limitations with Pinpoint this will continue to be an ongoing problem until the pinpoint issues are resolved. Until then it will be left to the developer to resolve manually via either a lambda which deletes unused endpoints, or manually storing endpoint ids and then using them when updating endpoints. 

Fundamental problem is that pinpoint seems to require a hard limit on the number of endpoints, while some use cases would seem to indicate no upper bound on endpoints for accurate data collection.

**Pull request closed without merging**
