### PR TITLE
feat: app client secret omission

### PR DESCRIPTION
**Pull request by ammarkarachi**
*Description of changes:*
Rework off reverted previous change https://github.com/aws-amplify/amplify-cli/pull/5992. This change sets the cognito default to generate the AppClientSecret to false and writes the secret to the native config files when the secret is configured in the app client.

The previous change did not take into consideration of an existing appClient with a configure client. In the new change the configuration files will possess the secret only if it's configured

*New Projects*
There will be two app clients same as before but the native app client will not be configured to generate a secret and the configuration file for IOS/Android will contain the secret either.

*Existing Projects with Auth Enabled*
The change will not affect any existing configuration of their app clients in Cognito. 

*Steps to test*

`yarn setup-dev`
`cd <project-folder>`

```
amplify-dev init
? Enter a name for the project testProject
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
```
### add auth
```
amplify-dev add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
```

### push

```
amplify-dev push  
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | tagsf536171d  | Create    | awscloudformation |
? Are you sure you want to continue? (Y/n) y
```

Auth is ready to use in your project

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jamesonwilliams — COMMENTED** [review]
Hold up!

Code changes themselves look good. Appreciate the use of a feature flag for this.

Please document this change in the PR description, and link any/all associated issues.

Also need to include a discussion of the previous change, why it was reverted, and how this change is different and is safe now.

There are also several related GitHub issues that should be referenced.

The change has potential to impact several other parts of the system and you should discuss this in the PR description.

We also need all of the client teams to sign-off on this change, confirming that they will function as-is, without an app client secret.

**Comment by royjit** [comment]
Step followed for testing:

``` console
yarn setup-dev
cd <project-folder>
amplify-dev --version
$ 4.41.1

amplify-dev init
? Enter a name for the project NoClientSecret
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Using default provider  awscloudformation

amplify-dev add auth
Using service: Cognito, provided by: awscloudformation

The current configured provider is Amazon Cognito.

Do you want to use the default authentication and security configuration? 
? Default configuration
Warning: you will not be able to edit these selections.
How do you want users to be able to sign in? 
? Username
Do you want to configure advanced settings? 
? No, I am done.

amplify-dev push
```

Checked both of the json configuration file and there is not client secret. 
Checked the Cognito console and there are two app clients created and both of them do not have client secret.

AWS iOS SDK testing:

1. SignIn without signup - Successful  (Returned user not found error)
2. Signup a user - Successful
3. Confirm Signup - Successful
4. Signin with the new user - Successful
5. Retreive Cognito User Pool tokens, Cognito Identity Pool ID, AWS Credentials - Successful

Test case 2 - HostedUI

```console
amplify-dev add auth
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM control
s (Enables per-user Storage features for images or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: noclientsecreta801
d5efa801d5ef
 Please enter a name for your identity pool. noclientsecreta801d5ef_identitypool_a801d5ef
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Please provide a name for your user pool: noclientsecreta801d5ef_userpool_a801d5ef
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use? noclientsecret
 Enter your redirect signin URI: myapp://
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: myapp://
? Do you want to add another redirect signout URI No
 Select the OAuth scopes enabled for this project. Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the social providers you want to configure for your user pool:
? Do you want to configure Lambda Triggers for Cognito? No
```
Checked both of the json configuration file and there is not client secret.
Checked the Cognito console and there are two app clients created and both of them do not have client secret.

AWS iOS SDK testing:

1. SignIn without signup - Successful  (Returned user not found error)
2. Signup a user - Successful
3. Confirm Signup - Successful
4. Signin with the new user - Successful
5. Retreive Cognito User Pool tokens, Cognito Identity Pool ID, AWS Credentials - Successful

**Comment by raphkim** [comment]
Confirmed the same from Android side using the above instructions

**Review by nikhname — APPROVED** [review]
lgtm

**Pull request merged**
