### PR TITLE
chore: Refine Dart config parsing

### PR DESCRIPTION
**Pull request by dnys1**
We are experimenting with some new config layouts and the current parsing behavior prevents changing the config structure. This expands on the current behavior to allow more flexibility in the config file contents.

### CODE REVIEW

**Review by Equartey — DISMISSED** [review]

**Comment by dnys1** [comment]
Hi @sobolk, sure I'd be happy to do that. Can you guide me on how I would set that up in this package?

**Comment by sobolk** [comment]
> Hi @sobolk, sure I'd be happy to do that. Can you guide me on how I would set that up in this package?

I suggest to look at other `amplify-frontend-xxx` packages. They have tests and these packages presumably exist for similar reasons `amplify-frontend-flutter` exists.

**Comment by dnys1** [comment]
@sobolk Done 👍

**Review by sobolk — DISMISSED** [review]

**Review by Equartey — DISMISSED** [review]

**Review by ragingsquirrel3 — APPROVED** [review]

**Review by danielleadams — APPROVED** [review]

**Comment by danielleadams** [comment]
There was an e2e test still failing, so I restarted the suite because I think the tests were stale.

**Comment by edwardfoyle** [comment]
Hi @dnys1 can you resolve the merge conflicts that have popped up? After that we can rerun the e2e tests to make sure those look good.

**Comment by dnys1** [comment]
@edwardfoyle Rebased on `dev` 👍

**Comment by dnys1** [comment]
Thanks @edwardfoyle. Tests are passing now.

**Comment by evcodes** [comment]
Running the changes through our e2e pipeline

**Comment by evcodes** [comment]
Within amplify-e2e-tests package, [there's a Readme](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-tests/Readme.md) that explains how to setup local e2e tests. I will warn you against trying to run many tests locally as they take a significant amount of time.

**Comment by sobolk** [comment]
```
[107.828,"o","\r\n\r\n\u001b[0m\u001b[31m\u001b[1mFollowing resources failed\u001b[22m\u001b[39m\u001b[0m\r\n\r\n"]
[107.828,"o","\u001b[1mResource Name:\u001b[22m amplify-notificationmigra-UpdateRolesWithIDPFuncti-izOWZmw1Ub1n (AWS::Lambda::Function)\r\n\u001b[1mEvent Type:\u001b[22m create\r\n\u001b[1mReason:\u001b[22m Resource handler returned message: \"The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: dae2cc6d-e402-4ae6-a927-2a5ef244cdaf)\" (RequestToken: c42094b0-9de5-6140-4b3a-f74e35534fa5, HandlerErrorCode: InvalidRequest)\r\n\r\n\r\n\u001b[1mResource Name:\u001b[22m amplify-notificationmigratio-inte-PinpointFunction-6cPBf6X57v1b (AWS::Lambda::Function)\r\n\u001b[1mEvent Type:\u001b[22m create\r\n\u001b[1mReason:\u001b[22m Resource handler returned message: \"The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 352b1442-9c61-40c3-a8ab-3e0645317104)\" (RequestToken: 7b332860-8981-eab3-aaea-0adea7452119, HandlerErrorCode: InvalidRequest)\r\n\r\n\r\n"]
```

Looks like we should upgrade some of our tests .

**Review by sobolk — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

**Pull request merged**
