### PR TITLE
Add project name to cognito user & identity pool name

### PR DESCRIPTION
**Pull request by dabit3**
*Issue #, if available:*
Issue #389

*Description of changes:*
Updated cognito project names to reflect names of client project.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dabit3** [comment]
@kaustavghosh06 what's the status on this? I'm having a hard time keeping up with these user pools when creating projects & knowing what belongs to what project. Would be pretty useful.

**Comment by kaustavghosh06** [comment]
@dabit3 I need to pull this PR in and run a few tests before merging it. I'll do it by this Friday EOD. Sorry that it took so long.

**Comment by dabit3** [comment]
@kaustavghosh06 awesome!

**Comment by kaustavghosh06** [comment]
@dabit3 I ran some tests and I found a case when auth deployments would fail due to this change. To avoid that, you might want to add some validation in after this line - https://github.com/aws-amplify/amplify-cli/blob/6ac2273bacb78627d4a357ac13c7f3badfb1475b/packages/amplify-category-auth/provider-utils/awscloudformation/index.js#L134

Add this after that line:
```
const disallowedChars = /[^A-Za-z0-9]+/g;
projectName = projectName.replace(disallowedChars, '');
```

**Comment by dabit3** [comment]
Thanks @kaustavghosh06 , let me know what you think!

**Pull request merged**
