### PR TITLE
feat: implement .autoUlid for testing purposes

### PR DESCRIPTION
**Pull request by ebisbe**
#### Description of changes
Add `$util.autoUlid()` function for Velocity template testing purposes.

#### Description of how you validated changes
Check the response has a Ulid format. Currently 26 characters from the [spec](https://github.com/ulid/spec)
#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ebisbe** [comment]
Hi @danielleadams,

I can add it as a PeerDependency, that should work right?
 Also I wanted to add the new 
 ```
 $util.autoKsuid() : String
Returns a 128-bit randomly generated KSUID (K-Sortable Unique Identifier) base62 encoded as a String with a length of 27.
``` 
Maybe you can discuss both cases as it would add a newer dependency as well.

**Review by edwardfoyle — APPROVED** [review]
LGTM! Thanks for the contribution @ebisbe 🥳

**Comment by danielleadams** [comment]
@ebisbe running our test suite on this and the I can approve. Thanks for your patience here!

**Comment by ebisbe** [comment]
@danielleadams I just saw your EDIT by chance ( edits don't trigger email notifications ). Do I need to do something for the rebase?

**Comment by danielleadams** [comment]
@ebisbe the PR needs to be rebased on `dev`.

**Comment by ebisbe** [comment]
@danielleadams done

**Review by danielleadams — APPROVED** [review]

**Comment by danielleadams** [comment]
Thanks @ebisbe - running our test suite on it and then this will be ready to merge.

**Comment by sdstolworthy** [comment]
@ebisbe Following up, it looks like there are a few merge conflicts that need to be resolved. We'd love to get this merged in. Would you mind tagging one of us once you have those resolved and we'll work to get this merged?

**Comment by ebisbe** [comment]
@sdstolworthy Merge conflict resolved.

**Review by sdstolworthy — APPROVED** [review]

**Review by sdstolworthy — DISMISSED** [review]

**Review by sobolk — DISMISSED** [review]

**Review by danielleadams — APPROVED** [review]

**Review by Amplifiyer — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

**Pull request merged**
