### PR TITLE
fix(cli): added global windows npm path to plugin import

### PR DESCRIPTION
**Pull request by slaat**
Global Plugins were not found under windows because the default path for node_modules is not inside a lib folder.

Description of changes:
I have added another global path, without the lib subfolder, for windows

Same changes, just for multienv as instructed by #784 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wizage** [comment]
I looked over this and why add another plugin search section
```
.plugins(globalNodeModulesDirPath, { matching: 'amplify-*', hidden: false })
.plugins(globalWindowsNodeModulesDirPath, { matching: 'amplify-*', hidden: false [})
```
when you can just add a simple check in the global-prefix file like so:
```
if (process.platform === 'win32') {
    return path.join(getNpmPrefix(), 'node_modules');
} else {
    return path.join(getNpmPrefix(), 'lib', 'node_modules');
}
```
This seems like an addition that can be avoided by adding the correct location straight to the global location.

**Comment by wizage** [comment]
@slaat Any thoughts on this change?

**Comment by slaat** [comment]
> @slaat Any thoughts on this change?

yes that makes way more sense. I will get to it ASAP

**Comment by slaat** [comment]
@kaustavghosh06 what do you think? Any idea when this will be merged?

**Comment by kaustavghosh06** [comment]
Hey @slaat,any reason why you got this closed. I was testing this PR and getting it to merge sometime this week.

**Comment by slaat** [comment]
I was under the impression that it should be done in the master branch,
since the whole env branch has been merged to it. I was about to do it
again there and submit another pull request.

**Comment by kaustavghosh06** [comment]
Yes, you're correct. Thanks!

**Comment by slaat** [comment]
Here you go: #941

**Pull request closed without merging**
