### PR TITLE
feat: add api status acm(access control matrix) subcommand and flag to help command

### PR DESCRIPTION
**Pull request by ykethan**
#### Description of how you validated changes
`amplify api status` had a flag `acm` which allows users to print a sub command matrix. the present help command does not contain this.

but it appears the `yarn build` is not picking up the help command changes. 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by danielleadams — CHANGES_REQUESTED** [review]
@ykethan are you able to add a test to this?

**Comment by ykethan** [comment]
> @ykethan are you able to add a test to this?

@danielleadams this is just adding to the help doc or the help command reference.

**Comment by danielleadams** [comment]
Right - but are there any tests that confirm the expected behavior from the code? Any tests that verify what is in the `commandsInfo` array? If this code gets deleted, how are we able to know?

**Comment by josefaidt** [comment]
Hey @danielleadams here is the test for the help functionality https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-cli-core/src/__tests__/help.test.ts. Ideally this documentation will be generated off of a command definition, which would ensure help documentation is always in sync with the command definition. However in the meantime we are maintaining this blob to print the known commands, subcommands, options, etc.

**Review by edwardfoyle — APPROVED** [review]

**Review by danielleadams — APPROVED** [review]

**Pull request merged**
