### PR TITLE
Reduce Python package size

### PR DESCRIPTION
**Pull request by tb102122**
#### Description of changes
extend file exclusion list to reduce package size

Issue #,
https://github.com/aws-amplify/amplify-cli/issues/5566
https://github.com/aws-amplify/amplify-cli/issues/9919
https://github.com/aws-amplify/amplify-cli/issues/10942 (partially)

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [X] Relevant documentation is changed or added (and PR referenced)
- [X] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danielleadams** [comment]
@tb102122 thanks for the contribution! Running our test suite it on it now.

**Comment by tb102122** [comment]
@danielleadams anything I have to do? It does not look like that this is related to my change. https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/10473/workflows/4f4cee01-0b70-400e-b7a3-b97a87590d24/jobs/343823/tests

**Comment by danielleadams** [comment]
@tb102122 I am starting it one more time, but it's unrelated, so no need to update anything.

**Review by danielleadams — APPROVED** [review]

**Review by edwardfoyle — APPROVED** [review]

**Comment by tb102122** [comment]
Great do you have any expected release date?

**Comment by CGarces** [comment]
Interesting, the change is merged but I sill see the pip folder with 2.1MB (compressed) in a lambda with no dependencies

image

The build was done with the amplify CI/CD upgraded to amplify 12.

**Pull request merged**
