### PR TITLE
fix: update error details in AmplifyFault during category push

### PR DESCRIPTION
**Pull request by Amplifiyer**
#### Description of changes

update error details in AmplifyFault during category push

#### Issue #, if available

N/A

#### Description of how you validated changes

N/A

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by evcodes — APPROVED** [review]
LGTM

**Review by danielleadams — COMMENTED** [review]
Do we have tests for this behavior? If so, would it be possible to add one or change one so that it fails if this is breaks?

**Comment by Amplifiyer** [comment]
> Do we have tests for this behavior? If so, would it be possible to add one or change one so that it fails if this is breaks?

Unfortunately there are no tests for this method (except for some trivial context tests). 

I can refactor this method in smaller units and export them to be testable, but ideally they shouldn't really be made public. I don't think I have an easy way to unit test this without exploding the scope of this PR.

**Review by danielleadams — APPROVED** [review]
That's what I figured. I'll approve since the level of effort to write a test overcomplicates the change.

**Pull request merged**
