### PR TITLE
fix: undefined appId destructuring

### LINKED ISSUE #6087: Cannot destructure property 'appId' of '_.get(...)' as it is undefined.
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm trying to use an environment on the cli but I get this error:

```
andres@DESKTOP-SKIUJ5M:~/Work/Logitool-Amplify-Project$ amplify env checkout master

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use logi
Cannot destructure property 'appId' of '_.get(...)' as it is undefined.
TypeError: Cannot destructure property 'appId' of '_.get(...)' as it is undefined.
    at persistLocalEnvConfig (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:408:11)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:180:5)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:144:24)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:43:22)
    at /home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/src/commands/env/checkout.ts:44:53
    at /home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Also, I tried:

```
andres@DESKTOP-SKIUJ5M:~/Work/Logitool-Amplify-Project$ amplify env pull --restore
⠹ Fetching updates to backend environment: master from the cloud.Could not initialize 'master': Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

But I have the credentials on the file .aws/credentials

This happens when I try to change of enviroment 

**Amplify CLI Version**
4.37.1

**Expected behavior**
Change the environment without problems

**Desktop (please complete the following information):**
 - OS: WSL 2
 - Node Version. v14.15.1

### PR DESCRIPTION
**Pull request by edwardfoyle**
*Issue #, if available:*
fixes #6087
*Description of changes:*
Default to {} instead of undefined in _.get() appId

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jhockett — APPROVED** [review]

**Comment by iuyt9003** [comment]
Please reopen, I am using 4.42.0 and still having this issue. 
`Cannot destructure property 'appId' of '_.get(...)' as it is undefined.`

**Comment by iuyt9003** [comment]
image

**Comment by iuyt9003** [comment]
@jhockett @edwardfoyle

**Comment by jhockett** [comment]
@iuyt9003 this is a pull request. There's nothing to reopen here. If you upgrade to the latest CLI and still see this error, please open a new issue so we can debug what's going on in your case.

**Pull request merged**
