### PR TITLE
fix: updated roleName in show auth ACM helper to include the groupClaim

### PR DESCRIPTION
**Pull request by naedx**
#### Description of changes

When @auth rules are defined with dynamic groups the roleName is identified by  `${rule.provider}:dynamicGroup:${groupsField}` which does not uniquely identify a valid @auth rule. 

The change updates the roleName to be defined as `${rule.provider}:dynamicGroup:${groupsClaim}:${groupsField}` which allows rules that differ by only the groupsClaim property to be appropriately distinguished from each other.

Unit tests have been added to verify the solution (which pass). Manual tests have been done with `amplify-dev` to verify the solution.

#### Issue #, if available

[#537](https://github.com/aws-amplify/amplify-category-api/issues/537) (aws-amplify/amplify-category-api)

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

#### Before Proposed Change:

<details>

```graphql

type Blog 
  @model 
  @auth(rules: [
    { allow: groups, groupsField: "tenantId", groupClaim: "custom:adminRole" }
    { allow: groups, groupsField: "tenantId", groupClaim: "custom:editorRole", operations: [read, update] }
  ])
{
  id: ID!
  name: String!
  tenantId: String!
}

``` 

PS *project-path*> amplify status api -acm Blog
✅ GraphQL schema compiled successfully.

Edit your schema at *project-path*\amplify\backend\api\testproject1\schema.graphql or place .graphql files in a directory at *project-path*\amplify\backend\api\testproject1\schema
🛑 @auth userPools:dynamicGroup:tenantId already exists for Blog

</details>

#### After Proposed Change:

<details>

```
*project-path*> amplify-dev status api -acm Blog
✅ GraphQL schema compiled successfully.

Edit your schema at *project-path*\amplify\backend\api\testproject1\schema.graphql or place .graphql files in a directory at *project-path*\amplify\backend\api\testproject1\schema

userPools:dynamicGroup:custom:adminRole:tenantId

  ┌──────────┬────────┬──────┬────────┬────────┐
  │ (index)  │ create │ read │ update │ delete │
  ├──────────┼────────┼──────┼────────┼────────┤
  │    id    │  true  │ true │  true  │  true  │
  │   name   │  true  │ true │  true  │  true  │
  │ tenantId │  true  │ true │  true  │  true  │
  └──────────┴────────┴──────┴────────┴────────┘

userPools:dynamicGroup:custom:editorRole:tenantId


  ┌──────────┬────────┬──────┬────────┬────────┐
  │ (index)  │ create │ read │ update │ delete │
  ├──────────┼────────┼──────┼────────┼────────┤
  │    id    │  false │ true │  true  │  false │
  │   name   │  false │ true │  true  │  false │
  │ tenantId │  false │ true │  true  │  false │
  └──────────┴────────┴──────┴────────┴────────┘
```

</details>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by pavellazar — APPROVED** [review]
LGTM,
Thank you for your contribution @naedx!

**Comment by naedx** [comment]
@lazpavel np!

Any updates on when this might be finally approved and integrated? I'd really like to use it in my project :)

**Review by danielleadams — APPROVED** [review]

**Comment by danielleadams** [comment]
@naedx thanks for the contribution! Running the test suite now.

**Comment by danielleadams** [comment]
@naedx do you mind rebasing?

**Comment by danielleadams** [comment]
Thank you @naedx - starting the test suite again.

**Pull request merged**
