### PR TITLE
fix(amplify-provider-awscloudformation): fix pinpoint region mappings

### LINKED ISSUE #2710: Analytics module region mapping are not up-to-date
Through AWS Console, I can create a pinpoint project in ap-southeast-2. When I add analytics through amplify cli, it created a project in region us-west-2. When I saw the cloudformation template, the regions mapping do effectively map ap-southeast-2 to us-west-2.

**Amplify CLI Version**
3.17.0

**To Reproduce**
* amplify configure (set ap-southeast-2 as project region)
* amplify add analytics (look at amplify/backend/analytics cloudformation file regions mapping)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Node Version. v10.17.0

### PR DESCRIPTION
**Pull request by ArionMiles**
fix #2710

*Issue #, if available:* #2710 (open) #4686 (closed)

*Description of changes:* 
Updated region mappings for Amazon Pinpoint. The analytics categories was added in the Amplify CLI since its first launch (Nov 2018), and at that time, Amazon Pinpoint was not available in many regions, so a lot of regions were mapped to `us-west-2`. Since then Pinpoint has become available in lots of regions, but adding `analytics` to the Amplify project would create the Pinpoint resource in `us-west-2` even if they were available in the user's default region.

The mappings have been updated by referring the [Service Endpoints page on AWS docs](https://docs.aws.amazon.com/general/latest/gr/pinpoint.html)

I've updated the region mappings in the below file, and tested it to work for `ap-south-1` region. I'm sure it'll also work for the other regions updated.
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js#L7-L26

**NOTE:** The same `serviceRegionMap` exists in the below file, but I've not updated it since it's not used by the CloudFormation templates.:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-core/src/utils/pinpoint.ts#L22-L41

Do let me know if I should update the maps in the second file as well.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by UnleashedMind** [comment]
@ArionMiles 
Thanks for your contribution.
This simple update can work with new pinpoint project setup. 
However, if a Pinpoint project is already set up for a backend env with an older version of the CLI, and then the client updates the Amplify CLI that has this region mapping update, there will be issues. 
For example, the region mapping is used by the notification category in the [getPinpointClient](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-notifications/lib/pinpoint-helper.js#L249) method through [getConfiguredPinpointClient](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js#L28), if a pinpoint project was created with older mappings, and then the client updates the CLI to have the new mappings, the client might not be able to correctly delete the pinpoint app, because the newer version of the CLI might point to another region due to the updated region mapping. 
Our team will have to thoroughly investigate the possible migration issues, add logic to handle them and write comprehensive tests around them when we update the region mappings.

**Comment by ArionMiles** [comment]
@UnleashedMind oh yeah, I hadn't considered the migration issues.

Any ideas as to how a migration policy could be designed to overcome this issue?
One quick fix could be that we don't migrate pinpoint applications for pre-existing backends and have a way to refer to the older mapping/region.

Of course, there might be users who would wish to migrate pinpoint applications and then we'd need to offer it to them as a choice, instead of doing it silently.

**Comment by ammarkarachi** [comment]
Hi @ArionMiles, you can possibly have the mapping use a [Feature Flag](https://docs.amplify.aws/cli/reference/feature-flags#configuration) to not break current projects already setup with the mapped regions.

**Comment by ArionMiles** [comment]
Hey @ammarkarachi thanks for this. I'm somewhat new to Amplify so is there any existing place where we're using feature flags that I could look at for a code example? I'd love to make this happen.

**Comment by jhockett** [comment]
> Hey @ammarkarachi thanks for this. I'm somewhat new to Amplify so is there any existing place where we're using feature flags that I could look at for a code example? I'd love to make this happen.

Feature flags are defined here, at the bottom of the file: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli-core/src/feature-flags/featureFlags.ts

Here's an example usage of a feature flag: https://github.com/aws-amplify/amplify-cli/blob/85b1ae31253d06718e13a2e2ff8cca3fc1931073/packages/amplify-frontend-ios/event-handlers/handle-PostCodegenModels.js

Docs on feature flags: https://docs.amplify.aws/cli/reference/feature-flags

**Comment by edwardfoyle** [comment]
Hi @ArionMiles we're working on additional region support and we'll have an update soon. We're going to close this as this new region support will override these changes.

**Pull request closed without merging**
