### PR TITLE
feat(amplify-provider-awscloudformation): add http default transformer

### PR DESCRIPTION
**Pull request by GustavoEdinger**
*Description of changes:*

Adding http transformer to default transformer list so we can start to use @http directive on the CLI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mikeparisstuff** [comment]
Can you please rebase this to fix the conflict?

**Comment by GustavoEdinger** [comment]
@mikeparisstuff Done =)

**Comment by mikeparisstuff** [comment]
@GustavoEdinger it looks like we may need one more rebase after we merged some PRs last friday.

**Comment by GustavoEdinger** [comment]
@mikeparisstuff  I'll write docs for this http directive 😉

**Pull request merged**
