### PR TITLE
Create: BatchSize and MaximumBatchingWindow parameters, V2 streaming lambda

### PR DESCRIPTION
**Pull request by marcvberg**
#### Description of changes
This creates new parameters for BatchSize and MaximumBatchingWindow on the Lambda streaming function from DynamoDB to ElasticSearch for the GraphQL Transformer vNext. The default values are 100 records and 2 seconds, respectively

#### Issue #, if available
#4695 

#### Description of how you validated changes
I created a local project and validated that the streaming function generated for a searchable contained the default values from the new parameters

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

Don't see unit testing capability for creating parameters, ready to take another look if needed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cjihrig** [comment]
> The default values are 100 records and 2 seconds, respectively

I think we should keep the current defaults. By making them configurable, the values can be tweaked during something like backfilling, and then re-configured for "normal" operation.

**Comment by marcvberg** [comment]
The case I would make for changing it is that it seems like it's not configurable at this point, we will need an additional change to pull in override parameters, and 100 is the default for DynamoDB EventSources already, we've just been overriding that.

Do we want to continue limiting it? The case I could see for it would be reducing the wait time for a single record to get to the streaming function, but increasing the batch size should bump throughput and cut cost by reducing API calls. Just want to consider benefits of both, or if there's a middle ground we think is better

**Comment by cjihrig** [comment]
OK. Maybe default `maxBatchingWindow` to one second then?

**Comment by marcvberg** [comment]
Sure, I can do that

**Review by cjihrig — APPROVED** [review]

**Pull request merged**
