### PR TITLE
feat!: hooks are no longer maintained in the s3 bucket

### PR DESCRIPTION
**Pull request by lazpavel**
#### Description of changes
- hooks files are no longer maintained in the s3 bucket
-- `amplify pull` no longer downloads and overrides hooks directory
-- `amplify push` / `amplify init` no longed uploads the hooks directory to the S3 bucket

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lazpavel** [comment]
release/merge to be coordinated with studio first

**Review by akshbhu — COMMENTED** [review]
PR looks good , but when changing env , Do we need to pull hooks from deployment bucket ?

**Comment by akshbhu** [comment]
Discussed offline

**Comment by Voyager-Two** [comment]
Using `amplifyPush --simple` in `amplify.yml` still overwrites `hooks` folder with S3 bucket `hooks` folder.

**Comment by lazpavel** [comment]
Hi @Voyager-Two, can you confirm that the Amplify CLI version in the Amplify Hosting build image settings is set to latest? Thank you

**Comment by Voyager-Two** [comment]
@lazpavel Yes it's set to latest.

**Comment by david10e** [comment]
hookissue

**Pull request merged**
