### PR TITLE
Appsync simulator/fix parse json

### PR DESCRIPTION
**Pull request by alex-vladut**
#### Description of changes

`$util.parseJson` function in the simulator doesn't follow the same logic as in Appsync when actually running the resolvers. The latter simply returns `null` when the input cannot be parsed. The only change I added it this one:

```js
  parseJson(value) {
    try {
      return JSON.parse(value);
    } catch (_) {
      return null;
    }
  }
```

all the rest if just due to code formatting.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by edwardfoyle — APPROVED** [review]
LGTM! thanks for the contribution @alex-vladut 😄

**Comment by danielleadams** [comment]
Hey @alex-vladut - changes look good. Running the test suite on it now.

**Comment by danielleadams** [comment]
Once the geo tests pass, this should be good to merge. the api_2 test was a known breakage on `dev` that has since been fixed (if we rebase we'll have to start the e2e over again).

**Review by danielleadams — APPROVED** [review]
The failed tests aren't related to the change, so going ahead and merging. Thanks @alex-vladut!

**Pull request merged**
