### PR TITLE
fix(graphql-key-transformer): optional id field if id not primary key

### LINKED ISSUE #6630: "Update" operation force input unnecessary fields
**Describe the bug**
it should only require the base table's primary key when running an update operation.

**To Reproduce**
```gql
type Review @model(subscriptions: { level: off })
@key(fields: ["owner", "serviceId"])
@key(name: "byService", fields: ["serviceId", "createdAt"], queryField: "listReviewsByService")
@key(name: "byStatus", fields: ["owner", "status", "createdAt"], queryField: "listReviewsByStatus")
@key(name: "byId", fields: ["id"], queryField: "listReviewsById")
{
    id: ID!
    serviceId: ID!
    owner: String!
    rating: Int
    title: String
    status: String
    createdAt: AWSDateTime!
}
```

↑gets this generated:
```gql
input UpdateReviewInput {
  id: ID!
  serviceId: ID!
  owner: String!
  rating: Int
  title: String
  status: String
  createdAt: AWSDateTime
}

input CreateReviewInput {
  id: ID
  serviceId: ID!
  owner: String!
  rating: Int
  title: String
  status: String
  createdAt: AWSDateTime
}

type Mutation {
  updateReview(input: UpdateReviewInput!, condition: ModelReviewConditionInput): Review
  ...
}
```

in the above example, the `id` filed is unnecessary in `UpdateReviewInput`, it should be the same as `CreateReviewInput`.

### PR DESCRIPTION
**Pull request by sharmaaditya570191**
#### Description of changes

The `graphql-key-transformer` was making the `id` field required in the schema built after running the command `amplify api gql-compile`. This happens in case when the `id` field is defined as a secondary index in the `graphql.schema`.

#### Issue #, if available

Fixes #6630 

#### Description of how you validated changes

Added a unit test for the case when `id` is defined as secondary index in `graphql` schema

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
@SwaySway can you have a look please?

**Comment by ammarkarachi** [comment]
CC: @SwaySway

**Review by SwaySway — COMMENTED** [review]
Changes look good!
Can we also include this for the delete resolver as well when the primary key is different?

**Comment by sharmaaditya570191** [comment]
> Can we also include this for the delete resolver as well when the primary key is different?

Sure.

**Comment by sharmaaditya570191** [comment]
@SwaySway I checked the delete input in the build schema. It is getting generated properly. I think the problem was only with update input types.

**Review by SwaySway — APPROVED** [review]
LGTM

**Pull request merged**
