### PR TITLE
ES VTL/nextToken Fix

### PR DESCRIPTION
**Pull request by SwaySway**
*Issue #, if available:*
#800 
*Description of changes:*
VTL Changes:
- Changed from to search_after to act as cursor when 'paginating' between results
- Sort will use field.keyword when the field type is a String 
  - Based on elastic search changes which now have fielddata set to false  [(ES Docs Resource)](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html).  

Schema Changes:
- nextToken is a string to fit with the search_after param

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brookslyrette** [comment]
@SwaySway Any plans to add those E2E tests? If not I can take a whack at it. 

cc: @mikeparisstuff Would be great to get this merged ASAP, right now sorting is broken for `@searchable` entities.

**Comment by brookslyrette** [comment]
@SwaySway Any plans to add those E2E tests? If not I can take a whack at it. 

cc: @mikeparisstuff Would be great to get this merged ASAP, right now sorting is broken for `@searchable` entities.

**Comment by wonkywonka** [comment]
Any news in regards to this? :)

**Comment by kaustavghosh06** [comment]
Hey guys, we're working on the integ e2e tests at the moment and as soon as its done, we'll merge and release a new version  of the CLI with this fix.

**Comment by SwaySway** [comment]
Added an e2e test which paginates and sorts using a string field.

**Pull request merged**
