### PR TITLE
chore: drop unnecessary execute permissions on some files

### PR DESCRIPTION
**Pull request by hirochachacha**
*Issue #, if available:*

*Description of changes:*

Convert some file permissions from 755 to 644.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kaustavghosh06** [comment]
What's the need for the change in the permissions? And what are the specific changes?

**Comment by hirochachacha** [comment]
@kaustavghosh06 This is a chore, not a fix. Although it's true to say we can write `readme.md` and `package.json` with execute permission, we usually don't want to. Simply because we don't execute these files. I take it as a honest mistake. I found it out by `find . -type f -perm -755 | grep -v -e node_modules -e bin -e scripts -e .sh`

**Comment by hirochachacha** [comment]
I changed the title. I hope it is clear now.

**Comment by hirochachacha** [comment]
I didn't change code, CI's failure should be unrelated.

**Comment by kaustavghosh06** [comment]
@hirochachacha Could you please rebase and update the PR?

**Comment by hirochachacha** [comment]
@kaustavghosh06 Done.

**Pull request merged**
