### PR TITLE
fix: resolve issues with graphiql explorer

### PR DESCRIPTION
**Pull request by dpilch**
#### Description of changes

See https://github.com/aws-amplify/amplify-cli/pull/13555. This PR supersedes the linked PR.

#### Issue #, if available

https://github.com/aws-amplify/amplify-category-api/issues/1269
https://github.com/aws-amplify/amplify-category-api/issues/1369

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by phani-srikar — APPROVED** [review]

**Comment by bombguy** [comment]
Retrying the failed e2e test

**Comment by 0618** [comment]
The e2e test l_function_3a_init_special_case_http_migration failure in [7db8321](https://github.com/aws-amplify/amplify-cli/pull/13691/commits/7db83212dbe407658b2dc4b56c622d06ddd4c90b) is a known issue caused by Go Runtime and will be fixed in https://github.com/aws-amplify/amplify-cli/pull/13671/

**Review by bombguy — APPROVED** [review]
LGTM

**Review by sobolk — APPROVED** [review]

**Comment by afnx** [comment]
Thank you everyone!

**Pull request merged**
