### PR TITLE
fix: add missing property layer version logical id to layer cloud state

### LINKED ISSUE #9636: Export to CDK: LogicalId missing for new layer version
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.8.3

### Amplify CLI Version

7.6.13

### What operating system are you using?

WSL Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual Changes Made

### Amplify Categories

auth, function

### Amplify Commands

export

### Describe the bug

`amplify export --out <export-cdk-project>` seems to throw an error

LogicalId missing for new layer version: <layer-name>

### Expected behavior

Exported Amplify Backend to CDK successful.

### Reproduction steps

`amplify export --out <export-cdk-project>`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by winstonwp**
Provide a solution for issue report #9636 where the error LogicalId missing for new layer version by
setting it on loadLayerDataFromCloud

fix #9636

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by winstonwp** [comment]
The E2E test failed due with the error `remote: Permission to aws-amplify/amplify-cli.git denied to github-actions[bot].` and this is out of my control, if you were so kind to let me know what I can do to fix this I would appreciate it.

**Comment by jhockett** [comment]
Hi @winstonwp, thank you for the contribution! The test failed because e2e tests are blocked from automatically running on PRs that have not been approved, so this is expected and not an issue.

I will try to review this in depth early next week. I want to ensure there are no side effects to flows unrelated to `export`.

**Comment by Punith13** [comment]
Hope this can be expedited, facing the same issue while trying to migrate amplify project to cdk resources.

**Comment by eliecer2000** [comment]
> Hope this can be expedited, facing the same issue while trying to migrate amplify project to cdk resources.

+1

**Review by jhockett — APPROVED** [review]
Thanks for the contribution @winstonwp, LGTM! Apologies for the delayed review.

**Review by johnpc — APPROVED** [review]

**Pull request merged**
