### PR TITLE
feat: add support for subscription arguments

### PR DESCRIPTION
**Pull request by vinodsr**
#### Description of changes

Filter the subscription response payload using the subscription arguments. Previously it was not considering the [subscription argument feature of appsync](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html#using-subscription-arguments)

#### Issue #, if available
NA

#### Description of how you validated changes
* Created a sample TODO application using `amplify-dev init`
* Added a new subscription using 
```
type Subscription {
  onCreateTodoWithArg(description: String): Todo
    @aws_subscribe(mutations: ["createTodo"])
}
```
* Run the mock `amplify-dev mock`
* Listen the subscription, Using [Altair Graphql Client](https://altair.sirmuel.design/). GraphiQL doesn't support the subscription
 ```
 subscription MySubscription {
  onCreateTodoWithArgs(description: "Wow") {
    id
    name
  }
  
}
 ```
* Ran the mutation for create TODO
* Only for the filtered payloads,  the subscription triggered
* Before making the change, the subscription gets triggered for any mutation for TODO
#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by sundersc — CHANGES_REQUESTED** [review]
Hi @vinodsr - Thanks for taking time to look into this. Could you please provide more details about the scope of change? If there is a GH issue (bug or feature-request) this PR addresses, please link it to the PR.

A quick feedback looking at the files changed.
- Only AppSync simulator package is modified. How about the AppSync resources on the cloud?
- The changes included in this PR is breaking the existing unit tests. Please go through the [contribution guide](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md) to find the steps to run the tests in local.
- Add unit tests for the new changes.

**Comment by vinodsr** [comment]
Hi @sundersc ,

> * Only AppSync simulator package is modified. How about the AppSync resources on the cloud?

Yes the cloud appsync already have this feature enabled and working fine. Only when we run local using simulator, filtering is not working , I am getting all responses of the subscription irrespective of the filtering

> * The changes included in this PR is breaking the existing unit tests. Please go through the [contribution guide](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md) to find the steps to run the tests in local.


I am unable to find out which test case went failed. Could you please point out which one ? 

I ran 
```
npm run test -- --scope amplify-appsync-simulator
```
and got the output 

```
➜ npm run test -- --scope amplify-appsync-simulator

> amplify-cli@0.1.0 test /home/vinod/work/amplify/amplify-cli
> lerna run test "--scope" "amplify-appsync-simulator"

lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "amplify-appsync-simulator"
lerna info filter [ 'amplify-appsync-simulator' ]
lerna info Executing command in 1 package: "yarn run test"
lerna info run Ran npm script 'test' in 'amplify-appsync-simulator' in 18.1s:
yarn run v1.18.0
$ jest
------------------------------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------
File                                            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                               
------------------------------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------
All files                                       |   63.46 |    42.77 |   58.15 |   63.83 |                                                                                                                                 
 src                                            |   86.84 |       85 |      72 |   87.96 |                                                                                                                                 
  index.ts                                      |   85.71 |    81.25 |   69.56 |   86.86 | 58-60,65,93-95,140,146-150,166                                                                                                  
  type-definition.ts                            |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/__tests__/__helpers__                      |   82.35 |       60 |    87.5 |   80.64 |                                                                                                                                 
  appsync-client.ts                             |   82.35 |       60 |    87.5 |   80.64 | 53-54,70,91,95,99                                                                                                               
 src/__tests__/velocity/util                    |     100 |      100 |     100 |     100 |                                                                                                                                 
  mock-data.ts                                  |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/data-loader                                |   84.21 |       50 |   66.66 |   84.21 |                                                                                                                                 
  index.ts                                      |   84.21 |       50 |   66.66 |   84.21 | 18,26,32                                                                                                                        
 src/data-loader/dynamo-db                      |    12.9 |        0 |    9.09 |   16.17 |                                                                                                                                 
  index.ts                                      |    12.9 |        0 |    9.09 |   16.17 | 20-26,31-59,64-74,79-103,106-132,139-156,161-180,183-209                                                                        
 src/data-loader/dynamo-db/utils                |   17.64 |        0 |       0 |   23.07 |                                                                                                                                 
  index.ts                                      |   17.64 |        0 |       0 |   23.07 | 4,8-33                                                                                                                          
 src/data-loader/lambda                         |   29.16 |        0 |      25 |   28.57 |                                                                                                                                 
  index.ts                                      |   29.16 |        0 |      25 |   28.57 | 7-10,14,18-31                                                                                                                   
 src/data-loader/none                           |     100 |       50 |     100 |     100 |                                                                                                                                 
  index.ts                                      |     100 |       50 |     100 |     100 | 5                                                                                                                               
 src/data-loader/opensearch                     |   66.66 |      100 |      50 |      60 |                                                                                                                                 
  index.ts                                      |   66.66 |      100 |      50 |      60 | 5-6                                                                                                                             
 src/resolvers                                  |   74.38 |       70 |   86.66 |   73.07 |                                                                                                                                 
  base-resolver.ts                              |      95 |      100 |     100 |   94.44 | 16                                                                                                                              
  function.ts                                   |   19.35 |        0 |   33.33 |   15.38 | 7-16,21-53                                                                                                                      
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
  pipeline-resolver.ts                          |   94.44 |    85.71 |     100 |   93.33 | 11,15                                                                                                                           
  unit-resolver.ts                              |   90.62 |     87.5 |     100 |   89.65 | 12,16,48                                                                                                                        
 src/schema                                     |   73.58 |       50 |   71.42 |      75 |                                                                                                                                 
  index.ts                                      |   73.58 |       50 |   71.42 |      75 | 36-54,75,106-108,114                                                                                                            
 src/schema/appsync-scalars                     |   55.31 |    33.33 |   36.36 |   54.44 |                                                                                                                                 
  index.ts                                      |   55.31 |    33.33 |   36.36 |   54.44 | 14-25,35-48,57-63,71-77,88-91,102-105,119,132,138-141,167-171,184,194-198,216-220,237-241                                       
 src/schema/directives                          |   95.23 |    73.52 |   96.96 |   95.69 |                                                                                                                                 
  auth.ts                                       |   92.18 |    68.75 |   95.45 |   93.33 | 47-48,57-58                                                                                                                     
  aws-subscribe.ts                              |     100 |    77.77 |     100 |     100 | 14-15,36                                                                                                                        
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/server                                     |   64.31 |    23.68 |   64.86 |   64.19 |                                                                                                                                 
  index.ts                                      |   94.44 |        0 |     100 |   93.93 | 40-44                                                                                                                           
  operations.ts                                 |    75.4 |    42.85 |   83.33 |   76.78 | 37,47,61,80,85-107                                                                                                              
  subscription.ts                               |   41.12 |    14.28 |   29.41 |   41.07 | 72-76,97-101,106-131,141-158,162-172,176-230                                                                                    
  websocket-subscription.ts                     |   97.05 |        0 |     100 |   96.42 | 52                                                                                                                              
 src/server/subscription/mqtt-server            |    27.2 |     12.4 |   16.85 |   25.89 |                                                                                                                                 
  abstract-listener.ts                          |   86.95 |    71.42 |   66.66 |      85 | 24,37-38                                                                                                                        
  client.ts                                     |    9.05 |        0 |    2.32 |    9.01 | 11-25,29-99,104-105,109-122,128-134,139-189,195-213,218-249,254,257-265,270-287,291-294,298-319,333-356,360-374,378-418,424-431 
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
  server.ts                                     |   46.95 |       25 |   24.13 |   45.28 | 121,126-133,137,141-146,153,163,174-180,185,189,193-235,240-263,270-271,277,282-284,289                                         
  trie-listener.ts                              |   45.45 |    41.66 |   22.22 |   48.14 | 20-22,26-32,36-38,41-43                                                                                                         
  util.ts                                       |   33.33 |        0 |       0 |   33.33 | 2-3                                                                                                                             
 src/server/subscription/websocket-server       |   90.21 |    69.23 |   96.87 |   96.29 |                                                                                                                                 
  message-type-guards.ts                        |   66.66 |    31.25 |     100 |   95.45 | 74                                                                                                                              
  message-types.ts                              |     100 |      100 |     100 |     100 |                                                                                                                                 
  server.ts                                     |   95.62 |    85.29 |   96.29 |   96.12 | 51,75,176,181,210                                                                                                               
 src/server/subscription/websocket-server/utils |     100 |      100 |     100 |     100 |                                                                                                                                 
  decode-header.ts                              |     100 |      100 |     100 |     100 |                                                                                                                                 
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/utils                                      |   54.54 |        0 |   66.66 |    62.5 |                                                                                                                                 
  expose-graphql-errors.ts                      |      50 |        0 |   66.66 |   57.14 | 15-18                                                                                                                           
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/utils/auth-helpers                         |    98.5 |    88.88 |     100 |   98.33 |                                                                                                                                 
  current-auth-mode.ts                          |     100 |     92.3 |     100 |     100 | 10                                                                                                                              
  helpers.ts                                    |   96.29 |    86.95 |     100 |      96 | 40                                                                                                                              
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
 src/utils/graphql-runner                       |   93.22 |    77.77 |     100 |    92.3 |                                                                                                                                 
  helpers.ts                                    |     100 |      100 |     100 |     100 |                                                                                                                                 
  index.ts                                      |     100 |      100 |     100 |     100 |                                                                                                                                 
  query-and-mutation.ts                         |     100 |    85.71 |     100 |     100 | 15                                                                                                                              
  subscriptions-filter.ts                       |     100 |       80 |     100 |     100 | 11                                                                                                                              
  subscriptions.ts                              |   77.77 |       60 |     100 |      75 | 20-22,38                                                                                                                        
 src/velocity                                   |    83.6 |    45.45 |     100 |   81.13 |                                                                                                                                 
  index.ts                                      |    83.6 |    45.45 |     100 |   81.13 | 60-71,87-92,110,130                                                                                                             
 src/velocity/util                              |   59.36 |    56.29 |   42.47 |   59.39 |                                                                                                                                 
  auth-utils.ts                                 |    92.3 |      100 |     100 |    90.9 | 15                                                                                                                              
  dynamodb-utils.ts                             |   10.25 |        0 |       0 |   11.42 | 8-97                                                                                                                            
  errors.ts                                     |   72.97 |    30.76 |   57.14 |   78.26 | 39-40,44-46                                                                                                                     
  general-utils.ts                              |   38.63 |    13.88 |   32.35 |      40 | 11-14,27-34,40-45,59-129                                                                                                        
  index.ts                                      |     100 |      100 |      25 |     100 |                                                                                                                                 
  info.ts                                       |     100 |      100 |     100 |     100 |                                                                                                                                 
  list-utils.ts                                 |     100 |      100 |     100 |     100 |                                                                                                                                 
  map-utils.ts                                  |   10.52 |        0 |       0 |   11.76 | 6-35                                                                                                                            
  math.ts                                       |     100 |      100 |     100 |     100 |                                                                                                                                 
  rds.ts                                        |     100 |    78.12 |     100 |     100 | 5-9                                                                                                                             
  str.ts                                        |     100 |      100 |     100 |     100 |                                                                                                                                 
  time.ts                                       |   69.44 |    58.33 |    90.9 |   67.64 | 14,21,35-45,60,67,76                                                                                                            
 src/velocity/util/transform                    |    8.45 |        0 |       0 |    9.52 |                                                                                                                                 
  dynamodb-filter.ts                            |    6.15 |        0 |       0 |    7.01 | 25-161                                                                                                                          
  index.ts                                      |   33.33 |      100 |       0 |   33.33 | 4-12                                                                                                                            
 src/velocity/value-mapper                      |   93.95 |    71.18 |   92.68 |   94.73 |                                                                                                                                 
  array.ts                                      |   96.55 |    58.06 |   94.11 |   97.87 | 59                                                                                                                              
  decimal.ts                                    |     100 |      100 |     100 |     100 |                                                                                                                                 
  integer.ts                                    |     100 |      100 |     100 |     100 |                                                                                                                                 
  map.ts                                        |   89.04 |       50 |    87.5 |   86.44 | 77-82,86,90,114                                                                                                                 
  mapper.ts                                     |   88.46 |    83.33 |     100 |   95.65 | 45                                                                                                                              
  string.ts                                     |   96.87 |      100 |    92.3 |   98.21 | 112                                                                                                                             
  to-json.ts                                    |     100 |      100 |     100 |     100 |                                                                                                                                 
------------------------------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------
Done in 17.89s.
lerna success run Ran npm script 'test' in 1 package in 18.1s:
lerna success - amplify-appsync-simulator
```

> * Add unit tests for the new changes.

I am working on adding new testcases for filtering

**Comment by vinodsr** [comment]
@sundersc i had pushed the test cases . Can you please have a look ?

**Comment by sundersc** [comment]
Thanks for getting back to us. Recently AppSync has released enhanced filtering capabilities and our team is working to include these capabilities into GraphQL transformer. This feature provides much more advanced filtering options which also requires some changes on the codegen and client libraries. I suggest to close this PR in favor of the work the team is doing across the libraries. I apologize for the miscommunication here and appreciate the time and effort that you've spent on this.
https://aws.amazon.com/blogs/mobile/appsync-enhanced-filtering/

**Pull request closed without merging**
