### PR TITLE
Fix for hasOne migration, and unit test

### PR DESCRIPTION
**Pull request by marcvberg**
#### Description of changes
Migrator was not correctly handling migration of relational directives without fields, added a unit test for our hasOne migration requirements

#### Description of how you validated changes
Running the migrator

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by danielleadams — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]

**Comment by cjihrig** [comment]
@marcvberg this has merge conflicts now.

**Comment by marcvberg** [comment]
@cjihrig Resolved

**Comment by cjihrig** [comment]
@marcvberg it looks like the CI is failing.

**Comment by marcvberg** [comment]
After a messy commit history, closing in favor of #8966

**Pull request closed without merging**
