### PR TITLE
Add variable support for user-defined resolver templates.

### PR DESCRIPTION
**Pull request by kevcam4891**
*Issue #, if available:*
Add variable support for user-defined resolver templates.
Pertains to #2092, #1946, maybe others.

*Description of changes:*
Certain resolver files depend on environment-specific variables, especially for
DynamoDB operations like BatchGetItem, where table references are required.
Since table names are dependent on the environment, user may now use 3 tokens
within the file that will resolve to their environment-specific values:

`{{env}}`: Environment name (Ex: develop, master)
`{{apiId}}`: GraphQLApiIdOutput (ex: shxxxvihabcj5hswrhxxxxxxxx)
`{{apiIdEnv}}`: Convenience method matching DynamoDB table name convention (ex: shxxxvihabcj5hswrhxxxxxxxx-develop)

With these tokens, you can now do something like:

ExampleObject.fieldName.req.vtl

```
#set($ids = [])
#foreach($id in ${ctx.source.userIds})
#set($map = {})
$util.qr($map.put("id", $util.dynamodb.toString($id)))
$util.qr($ids.add($map))
#end
{
"version" : "2018-05-29",
"operation" : "BatchGetItem",
"tables" : {
“ExampleTableName-{{apiIdEnv}}“: {
"keys": $util.toJson($ids),
"consistentRead": true
}
}
}
```

It would be nice to open this up to more replacement possibilities in the future, like being able
to use Cloudformation parameters, etc.

I welcome feedback if this is not an appropriate way to solve this challenge, but it seems useful to my workflow in that my resolvers adapt to the environment I'm in. Thanks!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kevcam4891** [comment]
Hi @attilah, any thoughts on this PR? I hope the intentions come across well in the example, but understand if maybe there is a better way long-term, to achieve the same effect. Let me know. Thanks!

**Comment by attilah** [comment]
@kevcam4891 sorry, the team is swamped right now, I'll raise this PR this week's bugbash to discuss it.

**Comment by kevcam4891** [comment]
@attilah my force push in my own repo caused this to close. I'll reopen it, but I'm curious, does this thing have legs? I'd really like to be able to use resolvers with Batch* DDB queries, and this seems to be the best way to do it. Especially when you're creating/cloning backends using the AWS console and you aren't pushing from your CLI where you can do all sorts of shell scripting to translate these values before a push. It'd need to be part of the amplify-cli that get downloaded by the instance that builds when you push to github and the console builds it out.

**Comment by tfendt** [comment]
@kevcam4891 Did this ever get merged? I too need a solution like this.

**Comment by kevcam4891** [comment]
@tfendt It never ended up getting merged, unfortunately. I never ended up getting feedback on this and since Amplify uses Amplify CLI to deploy, it was a blocker for me until it got merged. However, do not dispair!

A better solution in the end (for me at least) is to create a bash/node script that runs just prior to `amplify push`. I've got this script doing two things: 

- Converting YAML cloudformation files in my `amplify/backend/[api-name]/stacks-yaml` directory to `amplify/backend/[api-name]/stacks` using `cfn-flip` (https://github.com/awslabs/aws-cfn-template-flip). This has made making CFN files sooooo much easier, since amplify-cli does not yet support YAML files. Big game changer.

- Pertinent to this ticket, I've got a script that swaps all instances of {{apiIdEnv}} to its proper value, using the values in the `amplify/backend/amplify-meta.json` file.

The beauty with this setup, is this future proofs me against any sort of extra customizations I want to effect on my cloudformation templates before they get run. This is likely far better than trying to  do string replacements during the run itself.

Best practice is to create a bash alias that runs your pre-push script then follows it up with the push, so you just have to run:
```
apush="./prePushScript.sh && amplify push -y"
```

While you're at it, if you want to get extra fancy, make it play a system sound (mac example below) when the process finishes. For me this is great, because it takes 5-10 minutes for CFN to finish, and I want to start testing things right away -- however, I usually get distracted reading reddit or something while its running and 30 minutes later I remember to start working again. The sound should jolt you back to work :)

```
apush="./prePushScript.sh && amplify push -y && afplay /System/Library/Sounds/Ping.aiff"
```

You might need to tweak the && to || for sound to play regardless of whether the push succeeds or fails.

My YAML conversion script (some data may be redacted):
```
for i in `ls ./amplify/backend/api/[name]/stacks-yaml`;
    do
        cfn-flip -j ./amplify/backend/api/[name]/stacks-yaml/$i ./amplify/backend/api/[name]/stacks/${i%.*}.json;
    done
```

My resolver replacement script:
```
let fs = require("fs");
let amplifyMetaFile = "./amplify/backend/amplify-meta.json";
let localInfoFile = "./amplify/.config/local-env-info.json";
let resolverRawPath = "./amplify/backend/api/[name]/resolvers-raw";
let resolverPath = "./amplify/backend/api/[name]/resolvers";
let gqlID, env;

if (fs.existsSync(amplifyMetaFile) && fs.existsSync(localInfoFile)) {
  let fileJson = JSON.parse(fs.readFileSync(amplifyMetaFile));
  let localJson = JSON.parse(fs.readFileSync(localInfoFile));
  gqlID = fileJson.api.[name].output.GraphQLAPIIdOutput;
  env = localJson.envName;
}

let files = fs.readdirSync(resolverRawPath);
if (files.length > 0) {
  for (let file of files) {
    let read = fs.readFileSync(`${resolverRawPath}/${file}`).toString();

    // replace only if the variables exists and are available for use.
    if (gqlID && env) {
      read = read.replace("{{apiIdEnv}}", `${gqlID}-${env}`);
    }

    fs.writeFileSync(`${resolverPath}/${file}`, read);
  }
}
```

*Caveat:* The variables will not get replaced if you're creating a new backend from scratch. This is because you won't know the AppSync API ID or other details until it actually gets created. So when you first build a backend, you'll need to run this twice.

Hope this helps you and anyone needing some guidance on how to run batch queries in DynamoDB, but hopefully this offered some other workflow insights that are helpful as well.

Cheers.

**Comment by karrettgelley** [comment]
@kevcam4891 This is a hacky solution, but I love it. Work with what you got. Any word on whether or not this is still the accepted workaround?

**Pull request closed without merging**
