### PR TITLE
fix(graphql-model-transformer): implemented support for nested non model fields

### PR DESCRIPTION
**Pull request by lazpavel**
#### Description of changes
- implemented support for nested non model fields
- added unit test
- contains changes from #7879 

#### Description of how you validated changes
- `yarn test` passes

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cjihrig** [comment]
Can you rebase this please.

**Review by cjihrig — APPROVED** [review]
Can you add a call to `validateModelSchema()` in the test. Other than that, LGTM.

**Comment by cjihrig** [comment]
It looks like LGTM is having some issues with this PR as well.

**Comment by lazpavel** [comment]
already merged as part of https://github.com/aws-amplify/amplify-cli/pull/7927

**Pull request closed without merging**
