### PR TITLE
fix: lambda timeout should be an integer type

### PR DESCRIPTION
**Pull request by michaelbrewer**
#### Description of changes

Currently the generated cloudformation json/yaml have timeout as a string

#### Description of how you validated changes

Run cfn-lint against the generated CFN 

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [X] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by yuth — APPROVED** [review]
Thank you for the contribution

**Comment by ammarkarachi** [comment]
@michaelbrewer Can you address the conflicts?

**Comment by michaelbrewer** [comment]
> @michaelbrewer Can you address the conflicts?

@ammarkarachi done :)

**Comment by michaelbrewer** [comment]
@ammarkarachi  build it failing for some reason?

**Comment by ammarkarachi** [comment]
@michaelbrewer I see some unresolved conflicts

**Comment by michaelbrewer** [comment]
> @michaelbrewer I see some unresolved conflicts 

Ok. I will look through this again.

**Comment by michaelbrewer** [comment]
@ammarkarachi  ok i merged in the latest.

**Comment by michaelbrewer** [comment]
I am seeing unrelated build errors for this:

```javascript
amplify-category-auth: $ tsc
amplify-category-storage: $ tsc
amplify-category-auth: src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts:270:41 - error TS2322: Type '"email"' is not assignable to type 'UsernameAttributes'.
amplify-category-auth: 270   [CognitoUserPoolSigninMethod.EMAIL]: ['email'],
amplify-category-auth:                                             ~~~~~~~
amplify-category-auth: src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts:271:48 - error TS2322: Type '"phone_number"' is not assignable to type 'UsernameAttributes'.
amplify-category-auth: 271   [CognitoUserPoolSigninMethod.PHONE_NUMBER]: ['phone_number'],
amplify-category-auth:                                                    ~~~~~~~~~~~~~~
amplify-category-auth: src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts:272:58 - error TS2322: Type '"email"' is not assignable to type 'UsernameAttributes'.
amplify-category-auth: 272   [CognitoUserPoolSigninMethod.EMAIL_AND_PHONE_NUMBER]: ['email', 'phone_number'],
amplify-category-auth:                                                              ~~~~~~~
amplify-category-auth: src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts:272:67 - error TS2322: Type '"phone_number"' is not assignable to type 'UsernameAttributes'.
amplify-category-auth: 272   [CognitoUserPoolSigninMethod.EMAIL_AND_PHONE_NUMBER]: ['email', 'phone_number'],
amplify-category-auth:                                                                       ~~~~~~~~~~~~~~
amplify-category-auth: Found 4 errors.
amplify-category-auth: error Command failed with exit code 2.
amplify-category-auth: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by michaelbrewer** [comment]
@ammarkarachi should be all synced up and good to go.

**Comment by michaelbrewer** [comment]
@ammarkarachi  - Can we merge this next?

**Comment by jhockett** [comment]
Thanks for the contribution @michaelbrewer!

**Pull request merged**
