### PR TITLE
feat(graphql-dynamodb-transformer): add DyanmoDB point in time recovery

### PR DESCRIPTION
**Pull request by johnf**
*Description of changes:*
Adds an option to turn on point in time recovery for DyanmoDB.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by johnf** [comment]
I would also be tempted to make this just on by default but added it as a feature for now

**Comment by mikeparisstuff** [comment]
The code changes look good but it would be great to have an e2e test that covers this scenario. Since we have many e2e tests that include @model directives, can you change one of them such that it uses this extra flag in parameters.json? One such place is to pass the ShouldUsePointInTimeRecovery parameter inside the empty object on this line: https://github.com/yuth/amplify-cli/blob/9d19d819cf1f1f1452419465dc0069a2cc781b20/packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts#L94.

**Comment by johnf** [comment]
Done. Also ran the test and confirmed that the table is being created with PITR on.

**Comment by mikeparisstuff** [comment]
Looks good!

**Pull request merged**
