### PR TITLE
feat(category-geo): add new map style 2022.12

### PR DESCRIPTION
**Pull request by dayjournal**
#### Description of changes

- New map styles were added.
  - "VectorOpenDataStandardLight"

test
map

#### Issue #, if available

https://github.com/aws-amplify/amplify-cli/issues/11620

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by evcodes** [comment]
Overall PR looks good to merge. I am going to investigate why the tests are failing and get back to you.

**Comment by evcodes** [comment]
Can you please run yarn extract-api and add changes to API.md to this PR. This should fix the failing test

**Comment by dayjournal** [comment]
Hi, @evcodes . I have modified API.md.

**Review by evcodes — APPROVED** [review]
thanks for your continued contribution

**Review by goldbez — APPROVED** [review]

**Comment by dayjournal** [comment]
Hi, @evcodes .
This merged pull request does not appear to be included in the v10.6.0 release.
When is it scheduled to be released?

**Pull request merged**
