### PR TITLE
enhance(mock): print dynamodb-local endpoint url when running mock

### PR DESCRIPTION
**Pull request by j1mr10rd4n**
*Issue:*
NA

*Description of changes:*
Adds a line to the `mock` command output, printing the address of the dynamodb-local endpoint.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yuth** [comment]
@j1mr10rd4n could you rebase the PR

**Comment by edwardfoyle** [comment]
@j1mr10rd4n Can you rebase the PR?

**Comment by j1mr10rd4n** [comment]
Will do - apologies I missed the earlier rebase request.

**Comment by edwardfoyle** [comment]
Hi @j1mr10rd4n thanks again for the contribution! We have decided to close this PR because we have made some recent enhancements to mock and have added a section to our docs describing how to connect to a local mocked table: https://docs.amplify.aws/cli/usage/mock#connecting-to-a-mock-model-table. Because there are more steps required than simply curl-ing the URL, we think it may add confusion to print out the URL directly.

**Pull request closed without merging**
