### PR TITLE
feat: add nvmrc and usage doc for contributing

### PR DESCRIPTION
**Pull request by josefaidt**
#### Description of changes

Adds new dotfile, `.nvmrc`, to hold the suggested Node.js version for development. Also adds supporting documentation in `CONTRIBUTING.md` 

#### Issue #, if available

ref #8407 

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by josefaidt** [comment]
Hey y'all my apologies, totally missed these responses! Those are very valid points! Now that Node 16 is LTS would it be beneficial to change the hardcoded version to `14`? @danielleadams I didn't see this note in the CONTRIBUTING doc

**Comment by cjihrig** [comment]
> Now that Node 16 is LTS would it be beneficial to change the hardcoded version to 14?

Why would we hard code 14 instead of 16? I'm still a little skeptical about hard coding any version numbers. I foresee at least one Sev2 for us forgetting to update at some point.

**Comment by josefaidt** [comment]
> Why would we hard code 14 instead of 16?

I'm not able to build the CLI with node 16, but maybe this is due to some local configuration. We could add `lts` instead of a strict version number

**Comment by cjihrig** [comment]
> I'm not able to build the CLI with node 16

Ah, I see. I don't think it's an issue on your end. It looks like the version of `node-pty-prebuilt-multiarch` we use does not support Node 16 yet. It [looks like they are working on it](https://github.com/oznu/node-pty-prebuilt-multiarch/commits/prebuilt-multiarch).

I was just able to build on Node 16 with `node-pty-prebuilt-multiarch@0.10.1-pre.4`, but didn't do any testing to verify if it actually works as expected. It's also not ideal to depends on a pre-release if possible.

**Comment by josefaidt** [comment]
Hey @danielleadams I don't have strong opinions here, we can close

**Pull request closed without merging**
