### PR TITLE
chore(api): update api repo dependencies (DO NOT MERGE - opened new PR targeting main branch)

### PR DESCRIPTION
**Pull request by sundersc**
Update API repo dependencies.

### CODE REVIEW

**Comment by alharris-at** [comment]
Yarn.lock isn't updated, did you run `yarn` after the `ncu` command?

**Review by danielleadams — APPROVED** [review]
LGTM pending tests / e2e passing

**Review by jhockett — APPROVED** [review]

**Review by jhockett — CHANGES_REQUESTED** [review]
Good catch @alharris-at, please run `yarn` and update the lockfile

**Review by alharris-at — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

**Comment by danielleadams** [comment]
@sundersc can we close this?

**Pull request closed without merging**
