### PR TITLE
fix(amplify-category-api): mantain ff in iam api policy

### PR DESCRIPTION
**Pull request by SwaySway**
when using the ff for generating the appsync iam policy use the old format if the ff is empty

ref #6675

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by attilah — CHANGES_REQUESTED** [review]
As the new permissions with real graphql api access does not have their associated e2e test, please add those to make sure whatever policies we generate, the types/mutations/queries will be accessible.

**Comment by SwaySway** [comment]
> As the new permissions with real graphql api access does not have their associated e2e test, please add those to make sure whatever policies we generate, the types/mutations/queries will be accessible.

Updated unit tests to check for the new format and an additional format to check the old format is still generated.

**Comment by SwaySway** [comment]
Discussed offline added e2e tests to check that lambda invoke works with FF enabled to `true` and `false`

**Review by edwardfoyle — APPROVED** [review]
LGTM. 👍  on the e2e tests

**Comment by kylekirkby** [comment]
Can we please get this merged and released..? I’m having to do horrible work arounds to be able to access graphql inside a lambda function. This was working fine before :/

**Pull request merged**
