### PR TITLE
fix(amplify-category-function): invoke lambda with each request

### PR DESCRIPTION
**Pull request by ericclemmons**
*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/issues/2493

*Description of changes:*

Previously, this PR cleared lambda caches by deleting them from the `require.cache`.

With ef962d64cf1c98436171a3c14489ef73fa3571ac, `amplify mock` S3 triggers will use the same `invoke` method as `@function` lambdas, removing the bug entirely.

Now, when a user runs `amplify mock`, they are able to make changes to the their lambda without restarting the process!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
FYI, there is an important drawback to this approach: **it doesn't have dependency tracking**.

Removing the cached `index.js` that has `require('./some-util.js')` will only "reload" `index.js`, while `./some-util.js` remains cached. (When researching tutorials & lambdas, they overwhelmingly referenced a single `index.js`.)

If we want to ensure this support is covered, there are a couple ways we can resolve this:

1. Iterate through `Object.keys(require.cache)` for all files under that root directory, removing those as well. (`node_modules`, too?)

1. Use [`hot-module-replacement`](https://github.com/sidorares/hot-module-replacement), which watches all file dependencies & reloads them for you.  (The drawback of this module is that there may be bugs, since there hasn't been much validation with it & `amplify mock`).

However, if we only need to be concerned with reloading `index.js`, then this PR is all we need. 👍

**Comment by yuth** [comment]
> FYI, there is an important drawback to this approach: **it doesn't have dependency tracking**.
> 
> Removing the cached `index.js` that has `require('./some-util.js')` will only "reload" `index.js`, while `./some-util.js` remains cached. (When researching tutorials & lambdas, they overwhelmingly referenced a single `index.js`.)

Just realized that mock does not use this method to run the lambda functions. It runs the lambda function by [forking](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/invoke.ts#L8-L19) and creating a subprocess, which means none of the modules get cached.

And as for `amplify mock function <function-name>` every execution is a new instance of Amplify CLI as CLI terminates as soon as function execution is complete.

**Comment by ericclemmons** [comment]
Funny you mentioned this: the method I changed seemed redundant with https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/invoke.ts#L8-L19, but I didn't know why both existed.

Now I'm trying to figure out why my manual validation was working on Friday... 🤔

**Comment by ericclemmons** [comment]
Alright, so this explains my confusion: `invoke.ts` seems to be called the first time, but not on subsequent calls.

I'll need to check into this more.

> Screen Shot 2019-10-07 at 3 22 25 PM

I checked out `master`, put in a simple `console.log('HOWDY #', 1);`, then started uploading images (which triggers the function).

Running `amplify mock`, I see it get logged only once:

```shell
❯ amplify mock
...SNIP...
Testing function locally
HOWDY # 1
Testing function locally
Testing function locally
...SNIP...
Testing function locally
Testing function locally
...SNIP...
Testing function locally
Testing function locally
```

Similarly, `amplify-dev mock` behaves the same:

```shell
❯ amplify-dev mock
...SNIP...
Testing function locally
HOWDY # 2
Testing function locally
Testing function locally
...SNIP...
Testing function locally
Testing function locally
...SNIP...
Testing function locally
Testing function locally
...SNIP...
Testing function locally
```

What led me here was [Testing function locally](https://github.com/aws-amplify/amplify-cli/blob/8b225c1f9f16fed303adaaa91831bac7752d579d/packages/amplify-category-function/provider-utils/awscloudformation/utils/invoke.js#L16).

Then, after checking out this branch (`ericclemmons:2493-clear-require-cache-between-lambda-invocations`), I added this logging:

```diff
diff --git a/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js b/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
index eee1e9c..b2a3f20 100644
--- a/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
+++ b/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
@@ -18,7 +18,10 @@ const s3 = new aws.S3(

 const THUMBNAIL_FOLDER = 'thumbnails';

+console.log('trigger has been `require`d', 4);
+
 exports.handler = async function(event) {
+  console.log(`handler has been called`, 4);
   const [record] = event.Records;
   const { eventName } = record;
   const Bucket = record.s3.bucket.name;
```

Lastly, I ran `amplify-dev mock` and started uploading images again & making changes to my `console.log` statements:

```shell
❯ amplify-dev mock
...SNIP...
Testing function locally
trigger has been `require`d 2
handler has been called 2
Testing function locally
trigger has been `require`d 2
handler has been called 2
...SNIP...
Testing function locally
trigger has been `require`d 3
handler has been called 3
...SNIP...
Testing function locally
trigger has been `require`d 4
handler has been called 4
Testing function locally
trigger has been `require`d 4
handler has been called 4
...SNIP...
Testing function locally
trigger has been `require`d 4
```

In fact, I can't see any indication of the `fork` happening:

```diff
diff --git a/packages/amplify-util-mock/src/utils/lambda/invoke.ts b/packages/amplify-util-mock/src/utils/lambda/invoke.ts
index ae021931..15aee5de 100644
--- a/packages/amplify-util-mock/src/utils/lambda/invoke.ts
+++ b/packages/amplify-util-mock/src/utils/lambda/invoke.ts
@@ -2,6 +2,7 @@ import { fork } from 'child_process';
 import * as path from 'path';

 export function invoke(options) {
+    console.log("invoke", { options })
     return new Promise((resolve, reject) => {
         try {
             // XXX: Make the path work in both e2e and
```

Let me know if you'd like to do a call or screenshare on this.

**Comment by ericclemmons** [comment]
Just spoke with @yuth about this and the miss was that he was referencing `@function` invocations, while I was referencing the S3 lambda trigger ones.

The problem is that there are 2 different codepaths, and the one this PR addresses should be removed in favor of `utils/lambda/invoke.ts`.

**Comment by ericclemmons** [comment]
@yuth Tested this with my local project and confirmed it works:

```diff
diff --git a/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js b/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
index eee1e9c..1a0a966 100644
--- a/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
+++ b/samples/react/multi-category/photo-albums-e2e/amplify/backend/function/S3Trigger62f99b2e/src/index.js
@@ -16,9 +16,15 @@ const s3 = new aws.S3(
       }
 );

+let calls = 0;
+
+console.log('LAMBDA REQUIRED', __dirname, ++calls);
+
 const THUMBNAIL_FOLDER = 'thumbnails';

 exports.handler = async function(event) {
+  console.log('LAMBDA CALLED', __dirname, ++calls);
+
   const [record] = event.Records;
   const { eventName } = record;
   const Bucket = record.s3.bucket.name;
```

Now `amplify-dev mock` shows the following output while uploading/deleting images from S3:

```
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2
...SNIP...
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2
...SNIP...
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2
...SNIP...
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2
...SNIP...
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2
...SNIP...
LAMBDA REQUIRED .../amplify/backend/function/S3Trigger62f99b2e/src 1
LAMBDA CALLED .../amplify/backend/function/S3Trigger62f99b2e/src 2

```

**Comment by gaochenyue** [comment]
is it ready to merge?

**Comment by ericclemmons** [comment]
The PR was approved & I resolved conflicts, so going to merge this in 👍

**Comment by ericclemmons** [comment]
The build failed due to weird V8 issues unrelated to this PR.

**Comment by kaustavghosh06** [comment]
@ericclemmons Re-ran the build.

**Comment by ericclemmons** [comment]
Attempted a rebase via #3188, but still seeing the same V8 error, including locally by running `yarn`.

I _did_ notice that this generates changes in `yarn.lock` for this branch, so I ran `yarn` against `master` and saw non-committed changes to `yarn.lock` there too (including `node-gyp`!):

```diff
diff --git a/yarn.lock b/yarn.lock
index ba09b4791..476572761 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2989,11 +2989,6 @@
   resolved "https://registry.yarnpkg.com/@types/jest/-/jest-22.2.3.tgz#0157c0316dc3722c43a7b71de3fdf3acbccef10d"
   integrity sha512-e74sM9W/4qqWB6D4TWV9FQk0WoHtX1X4FJpbjxucMSVJHtFjbQOH3H6yp+xno4br0AKG0wz/kPtaN599GUOvAg==

-"@types/jest@23.1.0":
-  version "23.1.0"
-  resolved "https://registry.yarnpkg.com/@types/jest/-/jest-23.1.0.tgz#8054dd838ba23dc331794d26456b86c7e50bf0f6"
-  integrity sha512-DlIvvYDpcFgM1Ny1uzUBGb+0UMejhPEzDGxJ2By75ndMVDa82OUzPlV+v6NOsjA7HRvB4oj/Jqsscv6eJvLxeQ==
-
 "@types/jest@23.1.1":
   version "23.1.1"
   resolved "https://registry.yarnpkg.com/@types/jest/-/jest-23.1.1.tgz#c54ab1a5f41aa693c0957222dd10414416d0c87b"
@@ -3016,7 +3011,7 @@
   resolved "https://registry.yarnpkg.com/@types/jest/-/jest-23.3.14.tgz#37daaf78069e7948520474c87b80092ea912520a"
   integrity sha512-Q5hTcfdudEL2yOmluA1zaSyPbzWPmJ3XfSWeP3RyoYvS9hnje1ZyagrZOuQ6+1nQC1Gw+7gap3pLNL3xL6UBug==

-"@types/jest@^24.0.15", "@types/jest@^24.0.16", "@types/jest@^24.0.23":
+"@types/jest@^24.0.15", "@types/jest@^24.0.16", "@types/jest@^24.0.23", "@types/jest@^24.0.25":
   version "24.0.25"
   resolved "https://registry.yarnpkg.com/@types/jest/-/jest-24.0.25.tgz#2aba377824ce040114aa906ad2cac2c85351360f"
   integrity sha512-hnP1WpjN4KbGEK4dLayul6lgtys6FPz0UfxMeMQCv0M+sTnzN3ConfiO72jHgLxl119guHgI8gLqDOrRLsyp2g==
@@ -6834,7 +6829,7 @@ debug@3.1.0, debug@=3.1.0:
   dependencies:
     ms "2.0.0"

-debug@3.2.6, debug@^3.0.0, debug@^3.1.0, debug@^3.1.1, debug@^3.2.5, debug@^3.2.6:
+debug@3.2.6, debug@^3.0.0, debug@^3.1.0, debug@^3.1.1, debug@^3.2.5:
   version "3.2.6"
   resolved "https://registry.yarnpkg.com/debug/-/debug-3.2.6.tgz#e83d17de16d8a7efb7717edbe5fb10135eee629b"
   integrity sha512-mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==
@@ -6960,11 +6955,6 @@ deep-equal@^1.0.1, deep-equal@^1.1.1:
     object-keys "^1.1.1"
     regexp.prototype.flags "^1.2.0"

-deep-extend@^0.6.0:
-  version "0.6.0"
-  resolved "https://registry.yarnpkg.com/deep-extend/-/deep-extend-0.6.0.tgz#c4fa7c95404a17a9c3e8ca7e1537312b736330ac"
-  integrity sha512-LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==
-
 deep-is@~0.1.2, deep-is@~0.1.3:
   version "0.1.3"
   resolved "https://registry.yarnpkg.com/deep-is/-/deep-is-0.1.3.tgz#b369d6fb5dbc13eecf524f91b070feedc357cf34"
@@ -7117,11 +7107,6 @@ detect-indent@^5.0.0:
   resolved "https://registry.yarnpkg.com/detect-indent/-/detect-indent-5.0.0.tgz#3871cc0a6a002e8c3e5b3cf7f336264675f06b9d"
   integrity sha1-OHHMCmoALow+Wzz38zYmRnXwa50=

-detect-libc@^1.0.2:
-  version "1.0.3"
-  resolved "https://registry.yarnpkg.com/detect-libc/-/detect-libc-1.0.3.tgz#fa137c4bd698edf55cd5cd02ac559f91a4c4ba9b"
-  integrity sha1-+hN8S9aY7fVc1c0CrFWfkaTEups=
-
 detect-newline@^2.1.0:
   version "2.1.0"
   resolved "https://registry.yarnpkg.com/detect-newline/-/detect-newline-2.1.0.tgz#f41f1c10be4b00e87b5f13da680759f2c5bfd3e2"
@@ -10217,7 +10202,7 @@ husky@^3.0.3:
     run-node "^1.0.0"
     slash "^3.0.0"

-iconv-lite@0.4.24, iconv-lite@^0.4.17, iconv-lite@^0.4.24, iconv-lite@^0.4.4, iconv-lite@~0.4.13:
+iconv-lite@0.4.24, iconv-lite@^0.4.17, iconv-lite@^0.4.24, iconv-lite@~0.4.13:
   version "0.4.24"
   resolved "https://registry.yarnpkg.com/iconv-lite/-/iconv-lite-0.4.24.tgz#2022b4b25fbddc21d2f524974a474aafe733908b"
   integrity sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==
@@ -10413,7 +10398,7 @@ inherits@2.0.3:
   resolved "https://registry.yarnpkg.com/inherits/-/inherits-2.0.3.tgz#633c2c83e3da42a502f52466022480f4208261de"
   integrity sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=

-ini@^1.3.2, ini@^1.3.4, ini@^1.3.5, ini@~1.3.0:
+ini@^1.3.2, ini@^1.3.4, ini@^1.3.5:
   version "1.3.5"
   resolved "https://registry.yarnpkg.com/ini/-/ini-1.3.5.tgz#eee25f56db1c9ec6085e0c22778083f596abf927"
   integrity sha512-RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==
@@ -13728,15 +13713,6 @@ natural-compare@^1.4.0:
   resolved "https://registry.yarnpkg.com/natural-compare/-/natural-compare-1.4.0.tgz#4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7"
   integrity sha1-Sr6/7tdUHywnrPspvbvRXI1bpPc=

-needle@^2.2.1:
-  version "2.4.0"
-  resolved "https://registry.yarnpkg.com/needle/-/needle-2.4.0.tgz#6833e74975c444642590e15a750288c5f939b57c"
-  integrity sha512-4Hnwzr3mi5L97hMYeNl8wRW/Onhy4nUKR/lVemJ8gJedxxUyBLm9kkrDColJvoSfwi0jCNhD+xCdOtiGDQiRZg==
-  dependencies:
-    debug "^3.2.6"
-    iconv-lite "^0.4.4"
-    sax "^1.2.4"
-
 negotiator@0.6.2:
   version "0.6.2"
   resolved "https://registry.yarnpkg.com/negotiator/-/negotiator-0.6.2.tgz#feacf7ccf525a77ae9634436a64883ffeca346fb"
@@ -13906,22 +13882,6 @@ node-notifier@^5.2.1, node-notifier@^5.4.2:
     shellwords "^0.1.1"
     which "^1.3.0"

-node-pre-gyp@*:
-  version "0.14.0"
-  resolved "https://registry.yarnpkg.com/node-pre-gyp/-/node-pre-gyp-0.14.0.tgz#9a0596533b877289bcad4e143982ca3d904ddc83"
-  integrity sha512-+CvDC7ZttU/sSt9rFjix/P05iS43qHCOOGzcr3Ry99bXG7VX953+vFyEuph/tfqoYu8dttBkE86JSKBO2OzcxA==
-  dependencies:
-    detect-libc "^1.0.2"
-    mkdirp "^0.5.1"
-    needle "^2.2.1"
-    nopt "^4.0.1"
-    npm-packlist "^1.1.6"
-    npmlog "^4.0.2"
-    rc "^1.2.7"
-    rimraf "^2.6.1"
-    semver "^5.3.0"
-    tar "^4.4.2"
-
 node-releases@^1.1.29, node-releases@^1.1.44:
   version "1.1.45"
   resolved "https://registry.yarnpkg.com/node-releases/-/node-releases-1.1.45.tgz#4cf7e9175d71b1317f15ffd68ce63bce1d53e9f2"
@@ -14046,7 +14006,7 @@ npm-normalize-package-bin@^1.0.0, npm-normalize-package-bin@^1.0.1:
     semver "^5.6.0"
     validate-npm-package-name "^3.0.0"

-npm-packlist@^1.1.6, npm-packlist@^1.4.4:
+npm-packlist@^1.4.4:
   version "1.4.7"
   resolved "https://registry.yarnpkg.com/npm-packlist/-/npm-packlist-1.4.7.tgz#9e954365a06b80b18111ea900945af4f88ed4848"
   integrity sha512-vAj7dIkp5NhieaGZxBJB8fF4R0078rqsmhJcAfXZ6O7JJhjhPK96n5Ry1oZcfLXgfun0GWTZPOxaEyqv8GBykQ==
@@ -14077,7 +14037,7 @@ npm-run-path@^3.0.0:
   dependencies:
     path-key "^3.0.0"

-npmlog@^4.0.2, npmlog@^4.1.2:
+npmlog@^4.1.2:
   version "4.1.2"
   resolved "https://registry.yarnpkg.com/npmlog/-/npmlog-4.1.2.tgz#08a7f2a8bf734604779a9efa4ad5cc717abb954b"
   integrity sha512-2uUqazuKlTaSI/dC8AzicUck7+IrEaOnN/e0jd3Xtt1KcGpwx30v50mL7oPyr/h9bL3E4aZccVwpwP+5W9Vjkg==
@@ -16070,16 +16030,6 @@ raw-body@^2.2.0:
     iconv-lite "0.4.24"
     unpipe "1.0.0"

-rc@^1.2.7:
-  version "1.2.8"
-  resolved "https://registry.yarnpkg.com/rc/-/rc-1.2.8.tgz#cd924bf5200a075b83c188cd6b9e211b7fc0d3ed"
-  integrity sha512-y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==
-  dependencies:
-    deep-extend "^0.6.0"
-    ini "~1.3.0"
-    minimist "^1.2.0"
-    strip-json-comments "~2.0.1"
-
 react-app-polyfill@^1.0.4:
   version "1.0.5"
   resolved "https://registry.yarnpkg.com/react-app-polyfill/-/react-app-polyfill-1.0.5.tgz#59c7377a0b9ed25692eeaca7ad9b12ef2d064709"
@@ -18197,7 +18147,7 @@ tar-stream@^2.1.0:
     inherits "^2.0.3"
     readable-stream "^3.1.1"

-tar@^4.4.10, tar@^4.4.12, tar@^4.4.2, tar@^4.4.8:
+tar@^4.4.10, tar@^4.4.12, tar@^4.4.8:
   version "4.4.13"
   resolved "https://registry.yarnpkg.com/tar/-/tar-4.4.13.tgz#43b364bc52888d555298637b10d60790254ab525"
   integrity sha512-w2VwSrBoHa5BsSyH+KxEqeQBAllHhccyMFVHtGtdMpF4W7IRWfZjFiQceJPChOeTsSDVUpER2T8FA93pr0L+QA==
@@ -18581,7 +18531,7 @@ ts-jest@24.1.0:
     semver "^5.5"
     yargs-parser "10.x"

-ts-jest@^24.0.2, ts-jest@^24.2.0:
+ts-jest@^24.0.2, ts-jest@^24.2.0, ts-jest@^24.3.0:
   version "24.3.0"
   resolved "https://registry.yarnpkg.com/ts-jest/-/ts-jest-24.3.0.tgz#b97814e3eab359ea840a1ac112deae68aa440869"
   integrity sha512-Hb94C/+QRIgjVZlJyiWwouYUF+siNJHJHknyspaOcZ+OQAIdFG/UrdQVXw/0B8Z3No34xkUXZJpOTy9alOWdVQ==

```

**Pull request closed without merging**
