### PR TITLE
feat(amplify-frontend-javascript): add envName to awsExports

### PR DESCRIPTION
**Pull request by nubpro**
*Issue #, if available:*
#672 #6429

*Description of changes:*
To allow developers to access their current environment name on their frontend

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by attilah** [comment]
@nubpro thanks for the contribution, this change requires an API review from our part.

**Comment by sbue** [comment]
This would be very helpful!

**Comment by ivadenis** [comment]
@attilah any way you could get this reviewed and merged, please? 🙏

**Comment by mikeagent** [comment]
+1 to this

**Comment by apachler** [comment]
+1

**Comment by danielleadams** [comment]
Closing due to inactivity. Feel free to open another PR with these changes.

**Pull request closed without merging**
