### PR TITLE
Implement sorting on connection by implementing RANGE key

### PR DESCRIPTION
**Pull request by onlybakam**
Allows to specify `sortField` on a named connection crated by the
`@connection` directive. Has no effect on an unnamed connection.

```graphql
type Conversation @model {
  id: ID!
  messages: [Message]
    @connection(name: "ConvoMsgs", sortField: "createdAt")
}

type Message @model {
  id: ID!
  createdAt: AWSDateTime
  conversation: Conversation @connection(name: "ConvoMsgs")
}
```

Creates a GSI on the message table with hash key: `messageConversationId`
and range key `createdAt`

*Issue #, if available:* #127 

*Description of changes:*

- Update directive to accept sortField
- creates a range key for the GSI of the table of the associated type
- No effect if the connection is not named (need name to find the associated type)
- the sortField can be of any type that maps to a DynamoDB Scalar (not a list or boolean)
- Adds the sortField attribute to the attributeDefinitions list if it does not exist

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by undefobj** [comment]
@mikeparisstuff when reviewing this let's think about the interface consistency when compared to the @model type discussion from the other day. For instance in this PR `sortField` is in the argument, but an alternative implementation might be a directive on the field:

type Conversation @model {
  id: ID!
  messages: [Message]
    @connection(name: "ConvoMsgs")
}

type Message @model {
  id: ID!
  createdAt: AWSDateTime @sort 
  conversation: Conversation @connection(name: "ConvoMsgs")
}

This would be more consistent with the proposal in https://github.com/aws-amplify/amplify-cli/issues/56#issuecomment-416736520

Otherwise I think this does a good job at not leaking implementation of DDB into the transform as `@sort` or `sortField` are generic to the use case.

**Comment by mikeparisstuff** [comment]
I think this is a reasonable way to go about this to solve an evident customer pain point. In the future, I still think we can look into more advanced ways to configure key schemas of model types and can see a future where @connection takes an index as an argument instead of a sortField.

I.E. If I have a model type that looks something like this:

```
type Post @model {
  id: ID! @primary
  createdAt: String! @sort @sort(index: "blogIdIndex")
  blogId: @primary(index: "blogIdIndex")
}
```

Then I might use my pre-defined index:

```
type Blog @model {
  id: ID!
  posts: [Post] @connection(index: "blogIdIndex")
}
```

With this being said, I think this PR solves a pain point now and doesn't stop us from pursuing these advanced scenarios in the future so think we can work on getting this merged.

**Comment by mikeparisstuff** [comment]
Can we add an e2e test in the graphql-transformers-e2e-tests package for this?

**Comment by amlcodes** [comment]
this has killed me for weeks. would be helpful in docs

**Pull request merged**
