### PR TITLE
feat(amplify-category-auth): Support for UserMigration trigger

### PR DESCRIPTION
**Pull request by juniarz**
#### Description of changes

Added support for UserMigration custom function trigger.

#### Issue #, if available

#7333, #4577, #2989

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by houmark** [comment]
LGTM!!! :D @siegerts

**Comment by juniarz** [comment]
Thank you @houmark !

I am using the trigger on production, manually editing the generated CF file and unfortunately in v7+ it is not feasible anymore.

Hope this PR will be accepted!

It generates a function using the 'custom' module.

Developers who add this trigger is expected to make changes to the codes as the current 'custom' module triggers an error by default.

**Comment by houmark** [comment]
@renebrandel This is the only trigger missing for Auth/Cognito, I am not sure why this one was left out / forgotten in the first implementation of auth triggers, but it @juniarz did good work here, so we just need a review from the Amplify team to get this one merged.  Would be nice to see this one before it slides down the list.

**Comment by Amplifiyer** [comment]
Apologies for the delay in getting to this. Auth category now uses CDK for infrastructure provisioning and not CFN. Closing this since it uses CFN templates. We will look into adding this in our backlog.

**Pull request closed without merging**
