### PR TITLE
feat: add proxy support for amplify cli

### LINKED ISSUE #459: Proxy server support for amplify cli
We are working behind a corporate proxy. Unfortunately amplify does not seem to make use of the proxy server and we did not find any argument to pass in any proxy settings.

An argument or setting to set the proxy server to use would be nice.

The workaround we are currently using in linux is the tool proxychains, that is able to force any traffic of a command line tool through a configured proxy.

### PR DESCRIPTION
**Pull request by AlessandroVol23**
fix #459

*Issue #459*

*Description of changes:*
Add proxy support for amplify-cli.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kaustavghosh06** [comment]
@AlessandroVol23 Could you please update your PR based on @UnleashedMind's comments?

**Comment by AlessandroVol23** [comment]
PR is updated according to @UnleashedMind comments. I've ran into a problem that graphql was missing after merging the current master. Please check if it's working now with proxy support.

**Comment by kaustavghosh06** [comment]
@AlessandroVol23 Could you please rebase this PR? We're ready to merege this.

**Comment by AlessandroVol23** [comment]
Sorry, something wen't pretty wrong here. I'll create another branch from the current master with my changes, sorry!

**Comment by AlessandroVol23** [comment]
Opened a new PR with new branch. Sorry for that! #1464  I'll close that one

**Pull request closed without merging**
