### PR TITLE
fix: raise incorrect post event data

### PR DESCRIPTION
**Pull request by fossamagna**
#### Description of changes

Using an `AmplifyPostPushEventData` instance when raised a `PostInit` event, and an `AmplifyPostPushEventData` instance when raised a `InitEvent` event. These use the wrong event data for each other.
Fixed to use the correct event data.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danielleadams** [comment]
Hey @fossamagna - Thanks for the contribution! I see the function names were changed to match, but what is the context here? Was it breaking anything and was this intentional? Are there any tests we can add to ensure this works? Going to run the CLI test suite now.

**Comment by fossamagna** [comment]
@danielleadams Thank you for your review. 
I think that this change is not breaking, because `AmplifyPostPushEventData` and `AmplifyPostPushEventData ` is not same class, but both class is extended same parent class and both class no have property. 
I will add tests to ensure this work.

**Comment by fossamagna** [comment]
@danielleadams I added test for `execution-manager.ts`. It looks like there were nothing failures in the CI, Is there anything blocking to merging this PR?

**Review by jhockett — APPROVED** [review]

**Comment by hackmajoris** [comment]
Not sure if this issue is related, but I'll leave it here: https://github.com/aws-amplify/amplify-cli/issues/11021

**Pull request merged**
