### PR TITLE
feat(geo): add geo device location tracking walkthrough

### PR DESCRIPTION
**Pull request by sreeramsama**
#### Description of changes
Add create, update and remove walkthrough for geo device tracking with advanced settings

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [x] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [x] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danielleadams** [comment]
@sreeramsama there are merge conflicts now that need to be resolved - are you still working on this?

**Comment by sreeramsama** [comment]
> @sreeramsama there are merge conflicts now that need to be resolved - are you still working on this?

Not actively working on this PR as it is currently blocked. We are going through internal discussions in our team on some authorization design changes. There may be some changes we want to make on top of this PR.

**Comment by danielleadams** [comment]
@sreeramsama would you be able to close this PR and reopen with your changes when you are ready? The PR has already gotten stale.

**Comment by sreeramsama** [comment]
Sure, that works. Will close the PR for now and re-open when we start actively working on it.

**Pull request closed without merging**
