### PR TITLE
Added Flutter Admin UI support

### PR DESCRIPTION
**Pull request by renebrandel**
*Description of changes:*
- Enables `amplify pull --sandboxId <...>` for Flutter projects

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Ashish-Nanda — APPROVED** [review]
We tested this and the `amplify pull --sandboxId <...>` works now.

@fjnoyp is testing this a bit more end to end.

@kaustavghosh06 can we get this merged tomorrow?

**Comment by fjnoyp** [comment]
The codegen models look good.  ModelProvider.dart is not compiling because it's missing an implementation of "getModelTypeByModelName".  Once that is resolved this should be good to go.

**Comment by edwardfoyle** [comment]
Updated to include copying an empty `amplifyconfiguration.dart` file when initializing the flutter project. Wasn't sure what should be in the empty file so it has `{}` for now. Let me know what should be in there or update `amplifyconfiguration.empty.dart` in the PR with the expected contents

**Review by Amplifiyer — APPROVED** [review]

**Comment by phani-srikar** [comment]
> The codegen models look good. ModelProvider.dart is not compiling because it's missing an implementation of "getModelTypeByModelName". Once that is resolved this should be good to go.

To get the latest version of modelgen package for testing/debugging using `yarn setup-dev`, please update the dependency of `amplify-codegen` package on `@aws-amplify/appsync-modelgen-plugin` to the [latest stable version](https://www.npmjs.com/package/@aws-amplify/appsync-modelgen-plugin) example, currently it should be `"@aws-amplify/appsync-modelgen-plugin": "^1.22.6",`. Running `yarn setup-dev` then would update the lock file and use the latest modelgen. Note: Installing amplify CLI through npm or a self contained binary always fetches the latest version of dependencies and hence does not have this issue.

**Pull request merged**
