### PR TITLE
fix the amplify env checkout command

### LINKED ISSUE #2338: I cannot change to an env
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I try amplify status, I see that I use dev, when I try amplify env list I see that I have an qa env as well, when I try amplify checkout qa, I get the following error: Please pass in a valid environment name. Run amplify env list to get a list of valid environments.
When I try amplify env get --name qa, I do get the info of the qa env.

**To Reproduce**
1. amplify env add (follow the input steps and let's call it dev)
2. amplify status (this shows we use dev)
3. amplify env list (this shows dev)
4. amplify env add (follow the input steps and let's call it qa)
5. amplify status (this shows qa)
6. amplify env list (this shows dev and qa but qa with an * so we use qa)
3. amplify env checkout qa (this shows: Please pass in a valid environment name. Run amplify env list to get a list of valid environments.)

**Expected behavior**
Switch th the qa env with the amplify env checkout qa command.

**Additional context**
I use Cloud9

### PR DESCRIPTION
**Pull request by UnleashedMind**
*Issue #, if available:*
Fixes #2338 

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ben-elsen** [comment]
How can I upgrade my cli with this fix?

**Comment by kaustavghosh06** [comment]
We're shooting for end of day(PST) release.

**Comment by kaustavghosh06** [comment]
We released the latest version of the CLI - 3.8.0 with this fix.

**Comment by ben-elsen** [comment]
Awesome, thanks!

**Pull request merged**
