### PR TITLE
Load session using standard boto3 process

### PR DESCRIPTION
**Pull request by pecigonzalo**
This changes the script to use the normal boto3 process of loading creds (file, introspective api, env vars) if no explicit credentials are passed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ammarkarachi** [comment]
Can you give us more insight on what your use case is and why this change is necessary?. Also mention what gaps the previous method is this change filling

**Comment by pecigonzalo** [comment]
> Can you give us more insight on what your use case is and why this change is necessary? Also mention what gaps the previous method is this change filling

This is adding support to run this script in an EC2 or ECS which uses introspective API credentials, support running with `aws-vault` or other credential managers that expose the credentials as env-vars and also for users that already have the credentials on  `~/.aws/credentials`.

The previous method required me to pass the credentials explicitly, and it was also lacking support for STS sessions. 

I believe its best-practice to keep AWS CLIs and tools using the standard way of authenticating that most AWS tools use.

**Comment by kaustavghosh06** [comment]
@pecigonzalo Could you please resolve the merge conflicts if possible?

**Comment by pecigonzalo** [comment]
@kaustavghosh06 Is this going to be merged? If so Ill give it a go.

**Comment by pecigonzalo** [comment]
> @pecigonzalo Could you please resolve the merge conflicts if possible?

@kaustavghosh06 I have fixed the conflicts, is this going to be merged?

**Comment by pecigonzalo** [comment]
@ammarkarachi @kaustavghosh06 are you going to merge this or are you waiting for another merge conflict? It has been open for a year, you asked me to explain why this PR, I replied. Asked me to fix the conflicts after 6 months of not merging it, I did, and you dont even have the politeness to reply?

Such a disrespectful project with its collaborators.

**Comment by renebrandel** [comment]
Hi @pecigonzalo - first off, thank you so much for spending your time on authoring this PR. I'm really sorry for the delayed response on our end. We need to better at turning around PRs.

For this particular instance though, we have since planned to rearchitect the @searchable directive holistically. Reference: #7546 

Separately, we'll revisit our processes some more to make sure PR contribution get into the mainline faster and better. Apologies again for the current situation.

**Pull request closed without merging**
