### PR TITLE
feat(amplify-category-api): enable default 4xx and 5xx api gateway cors response

### LINKED ISSUE #5183: API Gateway setup for REST APIs has no CORS enabled for default 4xx and 5xx errors
**Describe the bug**
Current setup throws CORS errors to the client instead of the underlying 4xx or 5xx making debugging much difficult. This should also fix these issues: #5013, #4937

**Amplify CLI Version**
4.27.3

**To Reproduce**
Run `amplify add api` to create a new REST API for `/todos` on the root of a new project and follow the steps below

- Please select from one of the below mentioned services: __REST__
- Provide a friendly name for your resource to be used as a label for this category in the project: __todosApi__
- Provide a path (e.g., /book/{isbn}): __/todos__
- Choose a Lambda source __Create a new Lambda function__
- Provide a friendly name for your resource to be used as a label for this category in the project: __todosLambda__
- Provide the AWS Lambda function name: __todosLambda__
- Choose the runtime that you want to use: __NodeJS__
- Choose the function template that you want to use: __Serverless ExpressJS function__
- Do you want to access other resources in this project from your Lambda function? __No__
- Do you want to invoke this function on a recurring schedule? __No__
- Do you want to configure Lambda layers for this function? __No__
- Do you want to edit the local lambda function now? __Yes__
- Restrict API access __Yes__
- Who should have access? __Authenticated and Guest users__
- What kind of access do you want for Authenticated users? __create, read, update, delete__
- What kind of access do you want for Guest users? __read__
- Do you want to add another path? __No__

When trying to access `/items` (a non-existing route) it throws a CORS error
Screenshot 2020-08-18 at 17 13 46

**Expected behavior**
After enabling CORS for default 4xx and 5xx errors I get a more detailed response when trying `/items` (a non-existing route)
Screenshot 2020-08-18 at 17 19 29

Setting up CORS for 4xx and 5xx errors in API Gateway Console
Screenshot 2020-08-18 at 17 17 44
Screenshot 2020-08-18 at 17 18 03

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.7.0

**Additional context**
[Enable CORS with custom headers for an AWS Lambda function behind API Gateway](https://dev.to/leventov/enable-cors-with-custom-headers-for-an-aws-lambda-function-behind-api-gateway-in-serverless-framework-3702)

### PR DESCRIPTION
**Pull request by jamesaucode**
fix #5183

#### Description of changes
Enables CORS for default 4xx and 5xx api gateway for easier debugging.
It also allows `Amplify.API` to auto correct clockskew, see: https://github.com/aws-amplify/amplify-js/issues/6494

#### Issue #, if available
#5183

#### Description of how you validated changes
Manually tested.
Would be happy to add unit test if you can point me to where I should add the unit tests.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jhockett — APPROVED** [review]

**Comment by jamesaucode** [comment]
Added `@aws-cdk /assertions` for some unit test, please let me know if that's fine

**Comment by jhockett** [comment]
> Added `@aws-cdk /assertions` for some unit test, please let me know if that's fine

Should be fine, but if it's only needed for tests, it should be moved to devDependencies in `package.json`

**Comment by jamesaucode** [comment]
> > Added `@aws-cdk /assertions` for some unit test, please let me know if that's fine
> 
> Should be fine, but if it's only needed for tests, it should be moved to devDependencies in `package.json`

Good point, I will move them to `devDependencies` instead

**Review by jhockett — APPROVED** [review]

**Review by attilah — APPROVED** [review]
Changes LGTM, but it would be nice to add an E2E test to make sure deployed API will behave as expected for 4xx and 5xx responses.

**Comment by jamesaucode** [comment]
> Changes LGTM, but it would be nice to add an E2E test to make sure deployed API will behave as expected for 4xx and 5xx responses.

I can look to add some e2e tests for the changes

**Comment by jamesaucode** [comment]
@attilah added some e2e tests

**Pull request merged**
