### PR TITLE
fix: changing pinpoint policy

### PR DESCRIPTION
**Pull request by nikhname**
*Issue #, if available:*

*Description of changes:*
Change in pinpoint policy actions based on discussion

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ammarkarachi — APPROVED** [review]

**Comment by palpatim** [comment]
@nikhname, @kaustavghosh06 -- This change has caused customer issues on the client side, because customers can no longer remove endpoints once they hit the 10 endpoint limit. What is the expectation for customers to be able to remove endpoints?

**Comment by kayuapi** [comment]
+1, facing same issues as @palpatim

**Comment by bakalar** [comment]
Having the same issue. Why was getUserEndpoints removed?

**Comment by lawmicha** [comment]
this appears to be a corresponding JS library change https://github.com/aws-amplify/amplify-js/pull/7245
JS issue on client side after upgrading Amplify CLI https://github.com/aws-amplify/amplify-js/issues/7251

**Comment by GeorgeBellTMH** [comment]
Can we please get this and the corresponding change in js reverted? This is causing all sorts of problems...

**Comment by GeorgeBellTMH** [comment]
@ammarkarachi and @nikhname can you please give us some reasoning why this was done and what is being done to resolve this?

**Comment by GeorgeBellTMH** [comment]
Are we just going to leave this broken?

**Comment by thenderson55** [comment]
This is a serious issue that is causing a lot of problems.

**Pull request merged**
