### PR TITLE
chores(amplify-category-auth): signinwithapple fix

### PR DESCRIPTION
**Pull request by evcodes**
#### Issue #, if available
#11299 

#### Description of how you validated changes
ran through the CLI prompts

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Screen Shot 2022-10-31 at 4 59 33 PM

### CODE REVIEW

**Review by danielleadams — CHANGES_REQUESTED** [review]
Is there a test you can write for this?

**Comment by evcodes** [comment]
This is just changing the prompt, not sure if there's a test that can be added since this is for our internal prompt questions

**Review by lazpavel — APPROVED** [review]

**Review by akshbhu — APPROVED** [review]
Just check if we need similar prompt changes in e2e tests for this

**Comment by lazpavel** [comment]
> Just check if we need similar prompt changes in e2e tests for this
good point, @evcodes can you start the e2e on this one?

**Pull request merged**
