### PR TITLE
chore: bump auth lambda trigger runtime to node 14

### PR DESCRIPTION
**Pull request by edwardfoyle**
#### Description of changes

Bumps nested auth lambda trigger runtime to node 14. Also includes some lint updates

#### Issue #, if available
fixes: https://github.com/aws-amplify/amplify-cli/issues/10887

#### Description of how you validated changes
E2E suite running here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/node-runtime-bump
#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jhockett — APPROVED** [review]
LGTM

**Review by danielleadams — APPROVED** [review]

**Comment by joekiller** [comment]
Link to the failed test. https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/10276/workflows/eabdc976-17ea-4134-b3f6-8ed21089a022/jobs/334442/parallel-runs/0/steps/0-108

**Comment by danielleadams** [comment]
@edwardfoyle This is the test that is fixed https://github.com/aws-amplify/amplify-category-api/pull/731 right?

**Comment by edwardfoyle** [comment]
@danielleadams it will be fixed once we update our api category dependency to pull in the fix (hasn't happened yet). I think we can safely assume this change has passed e2e

**Comment by ajhool** [comment]
@edwardfoyle how does/will  this fix address node functions that were already deployed prior to the patch? Are those lambda functions automatically bumped to 14 on the next CLI push for the Auth module?

**Comment by joekiller** [comment]
My experience was the new template is rendered and deployed as a change on next push.

**Pull request merged**
